### PR TITLE
CAL-0712 Update to next dev version

### PR DESCRIPTION
**Pull request by andrewkfiedler**
#### What does this PR do?
Updates the ddf version to 2.15.0-SNAPSHOT

#### Who is reviewing it? 
@clockard 
@Bdthomson 
@shaundmorris 
@brjeter 
@rzwiefel 

#### How should this be tested?
(probably need this one in before https://github.com/codice/ddf/pull/4565)
CI Build

Fixes: https://github.com/codice/alliance/issues/712

### CODE REVIEW

**Comment by troymohl** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/<h2>Failed Tests: <span class='status-failure'>14</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance</a>: <span class='status-failure'>14</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationJpeg/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationJpeg</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationNitf/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationNitf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p001a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p001a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p002a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p002a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p004b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p004b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p009a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p009a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p010b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p010b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p012a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p012a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p014b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p014b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p016a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p016a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p102b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p102b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p104a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p104a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p106b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p106b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1068/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p011xa/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p011xa</strong></a></li></ul>
:x: JOB FAILURE

**Comment by bdeining** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/<h2>Failed Tests: <span class='status-failure'>14</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance</a>: <span class='status-failure'>14</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationJpeg/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationJpeg</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationNitf/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationNitf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p001a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p001a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p002a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p002a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p004b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p004b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p009a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p009a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p010b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p010b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p012a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p012a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p014b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p014b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p016a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p016a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p102b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p102b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p104a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p104a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p106b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p106b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1069/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p011xa/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p011xa</strong></a></li></ul>
:x: JOB FAILURE

**Comment by emmberk** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1070/
:white_check_mark: JOB SUCCESS

**Comment by emmberk** [comment]
:+1: Heroed with some smoke tests. Installed, modified a configuration, ingest something, searched for something. I did see this message in the logs, but it didn't appear to affect functionality:
```11:16:38,624 | INFO  | llerPollThread 0 | talog.source.solr.SolrMetacardClientImpl  460 | atalog-solr-provider | Solr exception getting content types
org.codice.solr.client.solrj.UnavailableSolrException: initializing 'catalog' client
	at org.codice.solr.factory.impl.UnavailableSolrClient.getProxiedClient(UnavailableSolrClient.java:38) ~[?:?]
	at org.codice.solr.factory.impl.SolrClientProxy.handle(SolrClientProxy.java:88) ~[?:?]
	at org.codice.solr.factory.impl.SolrClientProxy.query(SolrClientProxy.java:403) ~[?:?]
	at org.codice.solr.factory.impl.SolrClientProxy.lambda$query$46(SolrClientProxy.java:403) ~[?:?]
	at org.codice.solr.factory.impl.SolrClientAdapter.handle(SolrClientAdapter.java:276) ~[?:?]
	at org.codice.solr.factory.impl.SolrClientProxy.query(SolrClientProxy.java:403) ~[?:?]
	at ddf.catalog.source.solr.SolrMetacardClientImpl.getContentTypes(SolrMetacardClientImpl.java:404) ~[?:?]
	at ddf.catalog.source.solr.SolrCatalogProvider.getContentTypes(SolrCatalogProvider.java:147) ~[?:?]
	at ddf.catalog.source.solr.RemoteSolrCatalogProvider.getContentTypes(RemoteSolrCatalogProvider.java:113) ~[?:?]
	at Proxybc6cc888_2192_4f9c_a248_ea3c859d5110.getContentTypes(Unknown Source) ~[?:?]
	at org.codice.ddf.catalog.sourcepoller.ContentTypesSourcePollerRunner.getCurrentValueForSource(ContentTypesSourcePollerRunner.java:43) ~[?:?]
	at org.codice.ddf.catalog.sourcepoller.ContentTypesSourcePollerRunner.getCurrentValueForSource(ContentTypesSourcePollerRunner.java:25) ~[?:?]
	at org.codice.ddf.catalog.sourcepoller.SourcePollerRunner.lambda$getValueLoaders$0(SourcePollerRunner.java:60) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: org.codice.solr.client.solrj.UnavailableSolrException: initializing 'catalog' client
	at org.codice.solr.factory.impl.SolrClientAdapter.<init>(SolrClientAdapter.java:246) ~[?:?]
	at org.codice.solr.factory.impl.SolrClientAdapter.<init>(SolrClientAdapter.java:187) ~[?:?]
	at org.codice.solr.factory.impl.SolrClientAdapter.<init>(SolrClientAdapter.java:178) ~[?:?]
	at org.codice.solr.factory.impl.HttpSolrClientFactory.newClient(HttpSolrClientFactory.java:144) ~[?:?]
	at org.codice.solr.factory.impl.SolrClientFactoryImpl.lambda$new$0(SolrClientFactoryImpl.java:36) ~[?:?]
	at org.codice.solr.factory.impl.SolrClientFactoryImpl.newClient(SolrClientFactoryImpl.java:65) ~[?:?]
	at Proxy23e1f871_4e9d_40b0_a4d1_e0bc7a99c2f8.newClient(Unknown Source) ~[?:?]
	at ddf.catalog.solr.provider.SolrCatalogProvider.<init>(SolrCatalogProvider.java:29) ~[?:?]```

**Pull request merged**
