### PR TITLE
Update DDF version

### PR DESCRIPTION
**Pull request by clockard**
#### What does this PR do?
Updates DDF version for release.
#### Who is reviewing it? 
@emmberk @peterhuffer 
#### Choose 2 committers to review/merge the PR.

@brjeter 
@vinamartin
#### How should this be tested?
CI Build

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by clockard** [comment]
@emmberk The commits from the release process don't usually have a ticket number and I was going to lump this in under that umbrella. I can create a ticket and update the commit if you want.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/32/
:white_check_mark: JOB SUCCESS

**Pull request merged**
