### PR TITLE
CAL-475 Updated to embed hostname into CORBA IOR string rather than r…

### PR DESCRIPTION
**Pull request by beyelerb**
…elying on java getHost()

#### What does this PR do?
Allows the administrator to specify the hostname where CORBA objects can be reached. By default it was retrieving the system name using the java getHost() method which would often return localhost or 127.0.0.1 (not reachable from different machines). This also allows for proxy or port-forwarding situations.
#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)
#### Choose 2 committers to review/merge the PR.
(please choose ONLY two committers from below, delete the rest)

@clockard
@jlcsmith
#### How should this be tested?
Full build, the unit tests verify that the content of the IOR strings change based on setting the system host.
#### What are the relevant tickets?

[CAL-475](https://codice.atlassian.net/browse/CAL-475)
#### Checklist:
- [ ] Documentation Updated
- [X] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by beyelerb** [comment]
build now

**Comment by beyelerb** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1034/
:white_check_mark: JOB SUCCESS

**Pull request merged**
