### PR TITLE
CAL-828 Refactor for DDF security feature change

### PR DESCRIPTION
**Pull request by bakejeyner**
**This should be merged when upgrading to DDF version 2.26.0 or greater**

#### What does this PR do?
Changes Alliance to work with a security feature file refactor in DDF.

#### Who is reviewing it? 
@blen-desta 
@garrettfreibott 
@SmithJosh 
@stustison 

#### How should this be tested?
Startup:
1. Build [this branch of DDF](https://github.com/bakejeyner/ddf/tree/DDF-6166).
1. Build Alliance.
1. Run Alliance.
1. Login to the Admin Console to begin installation.
1. Install the Standard Profile.
1. Continue installation until the Single Sign On configuration page. Make changes to both the SAML and OIDC tabs.
1. Continue installation and restart the system when asked.

OIDC Authentication:
1. Setup a third party OIDC IdP for use with DDF. Message me for a guide on setting up Keycloak for use with DDF.
1. Navigate to the Admin Console -> Security -> Configuration.
1. In the OIDC Handler Configuration configuration, verify the changes you made during installation were persisted, then change the settings to match the IdP.
1. In the Web Context Policy Manager configuration, change Authentication Types for Endpoints to OIDC.
1. In an unauthenticated browser (incognito), navigate to https://localhost:8993/services/internal/metrics. You should successfully authenticate against the IdP and get a successful response. If you get a 403 try re-navigating to the page.

SAML Authentication:
1. Setup a third party SAML IdP for use with DDF. Message me for a guide on setting up CAS for use with DDF.
1. Navigate to the Admin Console -> Security -> Configuration.
1. In the IdP Client configuration, verify the changes you made during installation were persisted, then change the settings to match the IdP.
1. In the Web Context Policy Manager configuration, change Authentication Types for Endpoints to SAML.
1. In an unauthenticated browser (incognito), navigate to https://localhost:8993/services/internal/metrics. You should successfully authenticate against the IdP and get a successful response. If you get a 403 try refreshing the page.

PKI Authentication:
1. Make sure your browser is configured with a DDF trusted certificate. Feel free to contact me for more instruction on this step.
1. Navigate to the Admin Console -> Security -> Configuration.
1. In the Web Context Policy Manager configuration, change Authentication Types for Endpoints to PKI.
1. In an unauthenticated browser (incognito), navigate to https://localhost:8993/services. You should successfully authenticate using your trusted certificate and get a successful response.

LDAP Authentication:
1. Navigate to the Admin Console -> Security -> Configuration.
1. In the Security JAAS LDAP, set the following to hook up to an LDAP instance. Message me for a guide on hooking up to an LDAP instance.
1. In the Web Context Policy Manager configuration, change Authentication Types for Endpoints to BASIC.
1. In an unauthenticated browser (incognito), navigate to https://localhost:8993/services. You should successfully authenticate using an LDAP account’s credentials. If you get a 403 try refreshing the page.

Intrigue Smoke Test:
1. Install the DDF-UI. Feel free to contact me for more instruction on this step.
1. Login to Intrigue.
1. Bulk ingest a variety of records.
1. Create a new workspace. Name it whatever you want and save it.
1. In your workspace, create a new basic search with criteria that matches at least one of the ingested records. Confirm correct records are returned.
1. In your workspace, create a new wildcard (*) search. Confirm all records are returned.
1. Verify you can download the resource through the inspector.

#### What are the relevant tickets?
#828

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by SmithJosh** [comment]
Hero'd without Intrigue. Verified OIDC, SAML, PKI and LDAP auth work (LDAP after installing the `ldap-auth` feature). I couldn't get the UI to run on this PR branch, so for the smoke test I performed an ingest and search from the Karaf shell. Both behaved as expected. But I did not test:
- resource download
- workspace creation

**Comment by shaundmorris** [comment]
@bakejeyner what is the latest with this PR. Are you still planning on getting this PR merged?

**Review by stustison — APPROVED** [review]

**Comment by shaundmorris** [comment]
build now

**Comment by SmithJosh** [comment]
This is fixed by https://github.com/codice/alliance/pull/858

**Pull request closed without merging**
