### PR TITLE
CAL-474 Updated ha profile for updated feature name catalog-admin-poller-service

### PR DESCRIPTION
**Pull request by emmberk**
#### What does this PR do?
The name of a feature was updated in DDF in https://github.com/codice/ddf/pull/3790. This PR makes the same update in Alliance.
#### Who is reviewing it? 
@peterhuffer @kcover @brjeter 
#### Choose 2 committers to review/merge the PR.
@clockard
@vinamartin
#### How should this be tested?
Confirm that the `catalog-admin-poller-service` feature is successfully installed with Alliance on first start-up using the `feature:list` command in the Karaf console.
#### Any background context you want to provide?
The update to the feature name addresses some tech debt where the naming was inconsistent for the admin-poller-service bundle.
#### What are the relevant tickets?
[CAL-474](https://codice.atlassian.net/browse/CAL-474)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1015/
:x: JOB FAILURE

**Comment by emmberk** [comment]
```[ERROR] Failed to execute goal com.google.code.maven-replacer-plugin:replacer:1.5.3:replace (default) on project alliance: File '/jenkins/workspace/Alliance-Jobs/pr/Linux/distribution/alliance/target/dependencies/ddf-kernel-2.14.0-SNAPSHOT/etc/custom.system.properties' does not exist -> [Help 1]```

**Comment by emmberk** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1018/
:white_check_mark: JOB SUCCESS

**Comment by peterhuffer** [comment]
Successful hero on top of https://github.com/codice/ddf/pull/3790. ✅

**Pull request merged**
