### PR TITLE
CAL-782 fixed NitfPostProcessPlugin debug statement

### PR DESCRIPTION
**Pull request by shaundmorris**
#### What does this PR do?
Fixed SonarCloud finding of having not enough arguments. 
https://sonarcloud.io/project/issues?id=org.codice%3Aalliance&issues=AWTAnHm0xXt_iLiSlTNx&open=AWTAnHm0xXt_iLiSlTNx

#### Who is reviewing it? 
@oconnormi 
@glenhein 

#### Choose 2 committers to review/merge the PR.
(please choose ONLY two committers from below, delete the rest)

@brjeter
@clockard
@figliold

#### How should this be tested?
Build passes, analysis of the debug statement

#### What are the relevant tickets?
#782 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

---
This change is [Reviewable](https://reviewable.io/reviews/codice/alliance/783)

### CODE REVIEW

**Comment by shaundmorris** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1175/
:x: JOB FAILURE

**Comment by AdamBurstynski** [comment]
build now

**Comment by shaundmorris** [comment]
build now

rebased PR

**Comment by shaundmorris** [comment]
build now

previous build had a yarn build error

**Comment by shaundmorris** [comment]
build now

Previous build failed with some issue with a timeout building

**Comment by shaundmorris** [comment]
build now

Previous build failed with yarn issue

**Comment by shaundmorris** [comment]
build now

updated bot permissions on the repo for CI/CD builds

**Comment by shaundmorris** [comment]
build now 

Previous error: [2019-12-11T04:37:29.066Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.17:integration-test (default) on project test-itests-alliance: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.17:integration-test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?

**Pull request merged**
