### PR TITLE
[1.1.x]CAL-490 Fix the HA installation profile

### PR DESCRIPTION
**Pull request by brjeter**
#### What does this PR do?
- Fix the features themselves to declare their dependencies
- Include the additional dependencies in the ha profile for maintenance purposes
- Removes some features/bundles that no longer exist
#### Who is reviewing it? 
@Kjames5269  @paouelle 
#### Ask 2 committers to review/merge the PR and tag them here.
@coyotesqrl 
@figliold 
#### How should this be tested?
- Install with the HA profile: `profile:install ha`
- Install with the standard profile via both the UI and CLI
#### What are the relevant tickets?
[CAL-490](https://codice.atlassian.net/browse/CAL-490)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by brjeter** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/26/
:x: JOB FAILURE

**Comment by Kjames5269** [comment]
Hero'd ✅ 🎉

**Comment by brjeter** [comment]
build now (DDF artifacts are now deployed)

**Pull request merged**
