### PR TITLE
CAL-283 Catches exception that could cause thumbnail gen to fail

### PR DESCRIPTION
**Pull request by vinamartin**
Backport of https://github.com/codice/alliance/pull/288
@lessarderic @jlcsmith @figliold

### CODE REVIEW

**Comment by clockard** [comment]
Manual testing passed. Hero build passed with the exception of the NsiliSourceTest which looks like it is trying to pull in a bad version of ddf.catalog (2.11.0). This seems unrelated to this pr though.

**Comment by lessarderic** [comment]
ok to test

**Comment by lessarderic** [comment]
ok to test

**Comment by lessarderic** [comment]
test this please

**Pull request merged**
