### PR TITLE
CAL-207 Added mpg and mepg extensions to MPEG-TS Content Resolver

### PR DESCRIPTION
**Pull request by jlcsmith**
#### What does this PR do?
Maps .mpg and .mpeg to the video/mp2t mime type

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@bdeining @glenhein 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@kcwire 

#### How should this be tested?
1) Ingest .mpg and .mpeg files via the content directory monitor.  
2) Verify the resulting metacards have a metacard type of "isr:video".

#### What are the relevant tickets?

[CAL-207](https://codice.atlassian.net/browse/CAL-207)
#### Checklist:
- [ ] Documentation Updated
	- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by glenhein** [comment]
Not all mpg/mpeg files are MPEG-TS. They can also be MPEG-PS, which is not supported.

**Comment by jlcsmith** [comment]
@glenhein - when you say "not supported", does the transformer fail on them?  Or is it simply the case that no metadata is parsed out?  Is the resulting metacard in this case at least as good as what would come out of the TikeInputTransformer?

**Comment by glenhein** [comment]
I think it would try to ingest MPEG-TS packets, but would fail and keep trying until it worked through the entire file. I don't think it would throw a final exception indicating that the file couldn't be ingested, thus allowing the framework to try another input transformer.

**Comment by jlcsmith** [comment]
Currently we have a problem in that a lot of mpeg ts files come in with a ".mpg" extension.  Depending on the environment, they are likely to come in with a generic mime type like "application/octet-stream".  This is the rationale for this pull request.  I think there are additional improvements that can be made here.  For instance, the MPEGTS transformer could fail quickly on on non transport stream files.  Also, the REST endpoint should attempt all appropriate the transformers.  We have a ticket on the second issue already.

**Pull request merged**
