### PR TITLE
(0.2.x) CAL-265 Fixed overflow issues in Video Admin Plugin

### PR DESCRIPTION
**Pull request by bdeining**
#### What does this PR do?
This PR fixes overflow issues in the Video Admin Plugin
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@glenhein 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@andrewkfiedler 
@jlcsmith
#### How should this be tested?
Build / Install Experimental / Configure Stream with very large name and observe overflow handling
#### What are the relevant tickets?
[CAL-265](https://codice.atlassian.net/browse/CAL-365)
#### Checklist:
- [ ] Documentation Updated
- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by jlcsmith** [comment]
Need re-basing.  Also, I believe you need to update the td max-width per https://github.com/codice/alliance/pull/275/files#diff-1e277f283bb22a0f40aa9936ecc2bf5fR31

**Comment by jlcsmith** [comment]
build now

**Comment by bdeining** [comment]
@jlcsmith rebased and brought in changes from the master PR

**Comment by bdeining** [comment]
build now

**Comment by jlcsmith** [comment]
tested successfully

**Comment by bdeining** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Comment by bdeining** [comment]
build now

**Comment by bdeining** [comment]
build now

**Pull request merged**
