### PR TITLE
CAL-425 Resolved maven build warnings

### PR DESCRIPTION
**Pull request by idperez**
#### What does this PR do?
The current nightly builds of Alliance contain various warnings. These warnings may lead to build instability. This PR addresses them.

#### Who is reviewing it? 
@brjeter @blen-desta @bakejeyner 
#### Choose 2 committers to review/merge the PR.

@coyotesqrl 
@shaundmorris 
#### What are the relevant tickets?

[CAL-425](https://codice.atlassian.net/browse/CAL-xxx)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by idperez** [comment]
build now

**Comment by idperez** [comment]
build now

**Comment by brjeter** [comment]
build now

**Comment by idperez** [comment]
build now

**Pull request merged**
