### PR TITLE
CAL-506 Update MpegTsInputTransformer to set media type to video/mp2t

### PR DESCRIPTION
**Pull request by brjeter**
##### ABBREVIATED REVIEW BETWEEN 2.13.X AND MASTER IS IN EFFECT
Link to 1.1.x PR: #695 

#### Who is reviewing it? 
@tyler30clemens @austinsteffes 
#### Choose 2 committers to review/merge the PR.
@emmberk @jrnorth 
#### What are the relevant tickets?

[CAL-506](https://codice.atlassian.net/browse/CAL-506)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [X] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by brjeter** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1060/
:white_check_mark: JOB SUCCESS

**Comment by tyler30clemens** [comment]
Tested with https://github.com/codice/ddf/pull/4263

Verified there was no security manager issue and verified that the media type was `video/mp2t`
Hero Successful ✅

**Pull request merged**
