### PR TITLE
CAL-324 Adds configuration for failover alerts to logging config

### PR DESCRIPTION
**Pull request by vinamartin**
#### What does this PR do?
Overrides configuration made in https://github.com/codice/ddf/pull/2154

#### Who is reviewing it? 
@emmberk @mcalcote 

#### Choose 2 committers to review/merge the PR.
@clockard
@figliold

#### How should this be tested?
See original PR for instructions.

### CODE REVIEW

**Comment by vinamartin** [comment]
build now

**Comment by vinamartin** [comment]
build now

**Comment by clockard** [comment]
The three itests that failed are known issues not related to this pr

**Comment by vinamartin** [comment]
build now

**Comment by vinamartin** [comment]
build now

**Comment by vinamartin** [comment]
build now

**Comment by vinamartin** [comment]
build now

**Pull request merged**
