### PR TITLE
CAL-410 upgraded asciidoctor dependency

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

upgrades asciidoctor dependency from version 1.5.6 to 1.6.2

#### Choose 2 committers to review/merge the PR.
@clockard
@shaundmorris
@mcalcote 

#### How should this be tested?

builds successfully

#### Any background context you want to provide?

relies on https://github.com/codice/ddf/pull/6119

#### What are the relevant tickets?

[CAL-xxx](https://codice.atlassian.net/browse/CAL-xxx)
#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Comment by shaundmorris** [comment]
@ricklarsen does this need the DDF PR artifacts to build successfully?

**Comment by shaundmorris** [comment]
oh never-mind we need Glen's PR in first to get past the current build issue on this PR.

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Pull request merged**
