### PR TITLE
CAL-480 Updated SimpleSubject to override getName

### PR DESCRIPTION
**Pull request by AzGoalie**
#### What does this PR do?
Fixes the build by making SimpleSubject override getName.
#### Who is reviewing it? 
@ethantmanns @KalCramer 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)
#### Choose 2 committers to review/merge the PR.
(please choose ONLY two committers from below, delete the rest)

@clockard
@coyotesqrl
#### How should this be tested?
Build passes
#### What are the relevant tickets?

[CAL-480](https://codice.atlassian.net/browse/CAL-480)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by AzGoalie** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1026/
:x: JOB FAILURE

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1027/
:white_check_mark: JOB SUCCESS

**Pull request merged**
