### PR TITLE
Upgrade to DDF 2.22.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by shaundmorris**
#### What does this PR do?
Upgrades to DDF 2.20.0-SNAPSHOT

#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)
#### Choose 2 committers to review/merge the PR.
(please choose ONLY two committers from below, delete the rest)

@andrewkfiedler
@bdeining
@beyelerb
@brendan-hofmann
@brjeter
@clockard
@coyotesqrl
@figliold
@jlcsmith
@jrnorth 
@lessarderic
@millerw8
@pklinef
@ricklarsen - Documentation
@rzwiefel
@shaundmorris
@stustison
@vinamartin
#### How should this be tested?
Build passes

#### Any background context you want to provide?
DDF 2.21.0 was released

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

---
This change is [Reviewable](https://reviewable.io/reviews/codice/alliance/778)

### CODE REVIEW

**Comment by shaundmorris** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/<h2>Failed Tests: <span class='status-failure'>37</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance</a>: <span class='status-failure'>37</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testInvalidMarkings/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testInvalidMarkings</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleWordDoc/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleWordDoc</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testBannerMarkingMismatch/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testBannerMarkingMismatch</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleText/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleText</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingCodewordsAndDissem/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingCodewordsAndDissem</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testCosmicMarkingSimplePdf/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testCosmicMarkingSimplePdf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfWithoutImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfWithoutImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationJpeg/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationJpeg</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationNitf/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationNitf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidMtiNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidMtiNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidImageNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidImageNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGenerationThumbnailOnly/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGenerationThumbnailOnly</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p001a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p001a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p002a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p002a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p004b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p004b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p009a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p009a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p010b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p010b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p012a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p012a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p014b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p014b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p016a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p016a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p102b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p102b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p104a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p104a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p106b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p106b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p011xa/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p011xa</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testSubmitQuery/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testSubmitQuery</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrViaCallback/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrViaCallback</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrGetHitCount/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrGetHitCount</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testStandingQueryMgr/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testStandingQueryMgr</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/VideoTest/testStreamingVideo/'><strong>org.codice.alliance.test.itests.VideoTest.testStreamingVideo</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1169/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/VideoTest/testWithEmptyGeos/'><strong>org.codice.alliance.test.itests.VideoTest.testWithEmptyGeos</strong></a></li></ul>
:x: JOB FAILURE

**Comment by shaundmorris** [comment]
Build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/<h2>Failed Tests: <span class='status-failure'>37</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance</a>: <span class='status-failure'>37</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testInvalidMarkings/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testInvalidMarkings</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleWordDoc/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleWordDoc</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testBannerMarkingMismatch/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testBannerMarkingMismatch</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleText/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleText</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingCodewordsAndDissem/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingCodewordsAndDissem</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testCosmicMarkingSimplePdf/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testCosmicMarkingSimplePdf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfWithoutImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfWithoutImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationJpeg/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationJpeg</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationNitf/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationNitf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidMtiNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidMtiNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidImageNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidImageNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGenerationThumbnailOnly/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGenerationThumbnailOnly</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p001a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p001a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p002a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p002a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p004b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p004b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p009a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p009a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p010b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p010b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p012a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p012a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p014b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p014b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p016a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p016a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p102b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p102b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p104a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p104a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p106b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p106b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p011xa/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p011xa</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testSubmitQuery/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testSubmitQuery</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrViaCallback/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrViaCallback</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrGetHitCount/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrGetHitCount</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testStandingQueryMgr/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testStandingQueryMgr</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/VideoTest/testStreamingVideo/'><strong>org.codice.alliance.test.itests.VideoTest.testStreamingVideo</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1170/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/VideoTest/testWithEmptyGeos/'><strong>org.codice.alliance.test.itests.VideoTest.testWithEmptyGeos</strong></a></li></ul>
:x: JOB FAILURE

**Comment by shaundmorris** [comment]
Merging, since DDF 2.21.0-SNAPSHOT is no longer available.

**Pull request merged**
