### PR TITLE
CAL-490 Fix the HA installation profile

### PR DESCRIPTION
**Pull request by brjeter**
##### ABBREVIATED REVIEW BETWEEN 1.1.X AND MASTER IS IN EFFECT
Link to 1.1.x PR: #668 
 
#### Who is reviewing it? 
@Kjames5269 @paouelle 
#### Ask 2 committers to review/merge the PR and tag them here.
@coyotesqrl
@figliold 
#### What are the relevant tickets?
[CAL-490](https://codice.atlassian.net/browse/CAL-490)

### CODE REVIEW

**Comment by brjeter** [comment]
build now

**Comment by Kjames5269** [comment]
Hero'd ✅

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1041/
:white_check_mark: JOB SUCCESS

**Pull request merged**
