### PR TITLE
Fix UdpStreamMonitor update callback to set all properties

### PR DESCRIPTION
**Pull request by jrnorth**
#### What does this PR do?
Fix UdpStreamMonitor update callback to set all properties

#### Choose 2 committers to review/merge the PR.

@clockard
@glenhein 

#### How should this be tested?
Can be tested downstream @clockard 
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by jrnorth** [comment]
Will forward port this once it's approved and merged.

**Review by glenhein — APPROVED** [review]

**Review by clockard — APPROVED** [review]

**Comment by clockard** [comment]
build now

**Comment by jrnorth** [comment]
build now

**Comment by clockard** [comment]
✅ Manually tested and verified.

**Comment by jrnorth** [comment]
build now

**Pull request merged**
