### PR TITLE
CAL-291 fixed typo in dependency list docs and added a dependency check suppression

### PR DESCRIPTION
**Pull request by ricklarsen**
**PORT to `master` of PR #701**

#### What does this PR do?

fixes incorrect document type in dependency list docs. 

#### Who is reviewing it? 

@ahoffer @bakejeyner @blen-desta @garrettfreibott 

#### Choose 2 committers to review/merge the PR.
@clockard
@lessarderic
@ricklarsen - Documentation
@shaundmorris

#### How should this be tested?
builds successfully with dependency list included. 

#### What are the relevant tickets?

[CAL-291](https://codice.atlassian.net/browse/CAL-291)

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by mcalcote** [comment]
The description doesn't match the suppressions added for the security scan...

**Comment by ricklarsen** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1066/
:white_check_mark: JOB SUCCESS

**Pull request merged**
