### PR TITLE
CAL-334 removed the dependency flag on the catalog-core-api bundle to…

### PR DESCRIPTION
**Pull request by kcwire**
… ensure it is included in that kar.

#### What does this PR do?
allows the imaging-app to be installed on a vanilla DDF
#### Choose 2 committers to review/merge the PR.
@bdeining
@coyotesqrl
#### How should this be tested?
build alliance, startup a DDF 2.11 instance. Install imaging-app kar either through the deploy dir or the admin ui.
#### What are the relevant tickets?

[CAL-334](https://codice.atlassian.net/browse/CAL-334)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by coyotesqrl** [comment]
build now

**Comment by coyotesqrl** [comment]
I'll hero this...

**Comment by coyotesqrl** [comment]
Successfully heroed.

**Pull request merged**
