### PR TITLE
CAL-291 update to documentation unit test

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

updates documentation unit test to be more specific in the error text used to determine if a template error has occurred. 
#### Who is reviewing it? 
@ahoffer @austinsteffes @garrettfreibott 

#### Choose 2 committers to review/merge the PR.
@clockard
@coyotesqrl
@lessarderic
@ricklarsen - Documentation
@rzwiefel
@shaundmorris

#### How should this be tested?

builds successfully and test passes.

#### What are the relevant tickets?
[CAL-291](https://codice.atlassian.net/browse/CAL-291)
[DDF-4194](https://codice.atlassian.net/browse/DDF-4194)

#### Checklist:
- [ ] Documentation Updated
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by ricklarsen** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/24/
:x: JOB FAILURE

**Comment by ricklarsen** [comment]
previous build missing artifact, rerunning build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/25/
:x: JOB FAILURE

**Pull request merged**
