### PR TITLE
DDF-4675 Updated links to renamed validation parser

### PR DESCRIPTION
**Pull request by rzwiefel**
## NOTE
~https://github.com/codice/ddf/pull/4677 will need to be merged before this is merged.~ Merged.

-----

#### What does this PR do?
validationparser is now definitionparser. there were two names that needed to be updated. 
#### Who is reviewing it? 
@tbatie @glenhein @jordanwilking anyoneelse
#### How should this be tested?
build https://github.com/codice/ddf/pull/4677 and then ensure alliance builds and starts on top of it. 
#### What are the relevant tickets?
https://github.com/codice/ddf/pull/4677

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/<h2>Failed Tests: <span class='status-failure'>32</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance</a>: <span class='status-failure'>32</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/org_codice_alliance_test_itests_BannerMarkingsTest/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.org.codice.alliance.test.itests.BannerMarkingsTest</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfWithoutImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfWithoutImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationJpeg/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationJpeg</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationNitf/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationNitf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidMtiNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidMtiNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidImageNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidImageNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGenerationThumbnailOnly/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGenerationThumbnailOnly</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p001a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p001a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p002a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p002a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p004b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p004b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p009a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p009a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p010b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p010b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p012a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p012a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p014b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p014b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p016a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p016a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p102b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p102b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p104a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p104a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p106b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p106b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p011xa/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p011xa</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testSubmitQuery/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testSubmitQuery</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrViaCallback/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrViaCallback</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrGetHitCount/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrGetHitCount</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testStandingQueryMgr/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testStandingQueryMgr</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/VideoTest/testStreamingVideo/'><strong>org.codice.alliance.test.itests.VideoTest.testStreamingVideo</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1071/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ContainerPerSuiteItestSuite/org_codice_alliance_test_itests_ContainerPerSuiteItestSuite/'><strong>org.codice.alliance.test.itests.ContainerPerSuiteItestSuite.org.codice.alliance.test.itests.ContainerPerSuiteItestSuite</strong></a></li></ul>
:x: JOB FAILURE

**Comment by rzwiefel** [comment]
We'll need to build this locally pointing at the ddf branch to test before the ddf pr is merged.

**Comment by rzwiefel** [comment]
This may not succeed, but we can try - build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/<h2>Failed Tests: <span class='status-failure'>36</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance</a>: <span class='status-failure'>36</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testInvalidMarkings/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testInvalidMarkings</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleWordDoc/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleWordDoc</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testBannerMarkingMismatch/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testBannerMarkingMismatch</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleText/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleText</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingCodewordsAndDissem/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingCodewordsAndDissem</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testCosmicMarkingSimplePdf/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testCosmicMarkingSimplePdf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfWithoutImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfWithoutImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationJpeg/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationJpeg</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationNitf/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationNitf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidMtiNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidMtiNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidImageNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidImageNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGenerationThumbnailOnly/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGenerationThumbnailOnly</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p001a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p001a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p002a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p002a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p004b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p004b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p009a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p009a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p010b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p010b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p012a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p012a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p014b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p014b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p016a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p016a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p102b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p102b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p104a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p104a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p106b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p106b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p011xa/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p011xa</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testSubmitQuery/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testSubmitQuery</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrViaCallback/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrViaCallback</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrGetHitCount/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrGetHitCount</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testStandingQueryMgr/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testStandingQueryMgr</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1073/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/VideoTest/testStreamingVideo/'><strong>org.codice.alliance.test.itests.VideoTest.testStreamingVideo</strong></a></li></ul>
:x: JOB FAILURE

**Comment by rzwiefel** [comment]
Verified Failures are for a reason not related:
```org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=sample-content-metadata-extractor; type=karaf.feature; version="[1.2.0.SNAPSHOT,1.2.0.SNAPSHOT]"; filter:="(&(osgi.identity=sample-content-metadata-extractor)(type=karaf.feature)(version>=1.2.0.SNAPSHOT)(version<=1.2.0.SNAPSHOT))" [caused by: Unable to resolve sample-content-metadata-extractor/1.2.0.SNAPSHOT: missing requirement [sample-content-metadata-extractor/1.2.0.SNAPSHOT] osgi.identity; osgi.identity=sample-content-metadata-extractor; type=osgi.bundle; version="[1.2.0.SNAPSHOT,1.2.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve sample-content-metadata-extractor/1.2.0.SNAPSHOT: missing requirement [sample-content-metadata-extractor/1.2.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.codice.alliance.sdk.extraction)"]]```

**Pull request merged**
