### PR TITLE
CAL-344 Codebase Reformat

### PR DESCRIPTION
**Pull request by rzwiefel**
#### What does this PR do?
Re-formats alliance
#### Who is reviewing it? 
anyone
#### How should this be tested?
build
#### What are the relevant tickets?
[CAL-344](https://codice.atlassian.net/browse/CAL-344)
#### Checklist:
- [x] Documentation Updated

### CODE REVIEW

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by coyotesqrl** [comment]
Build now

**Comment by coyotesqrl** [comment]
Build now

**Comment by coyotesqrl** [comment]
Build now

**Comment by coyotesqrl** [comment]
Closed and replaced with #383

**Pull request closed without merging**
