### PR TITLE
CAL-473 Relocate test and maven utilities to other repos

### PR DESCRIPTION
**Pull request by paouelle**
#### What does this PR do?
It relocates various generic test and maven utilities to codice-test and codice-maven repositories.

#### Who is reviewing it? 
@AzGoalie 
@figliold
@tbatie 

#### Select relevant component teams: 
@codice/build 
@codice/test 

#### Ask 2 committers to review/merge the PR and tag them here.
@coyotesqrl
@lessarderic

#### How should this be tested?
* successful PR build should be sufficient

#### What are the relevant tickets?
[DDF-4166](https://codice.atlassian.net/browse/DDF-4166)
[CAL-473](https://codice.atlassian.net/browse/CAL-473)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by paouelle** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by paouelle** [comment]
build now - connection was reset

**Comment by LinkMJB** [comment]
Looks like that build failed due to timeout or disconnect while pulling from nvd.nist.gov -- their site is responding pretty slowly right now, so I won't be surprised if there is an outage announced soon.

**Comment by paouelle** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1022/
:white_check_mark: JOB SUCCESS

**Pull request merged**
