### PR TITLE
Backport 766 to 1.7.x

### PR DESCRIPTION
**Pull request by AdamBurstynski**
#### What does this PR do?

CAL-763 Updated the Jenkinsfile to better match what was happening in… the "old style" jobs we used before. (#1) (#762)

Overriding due to failed unit tests and improving the build

(cherry picked from commit babd7916611d5eb21c967387fc767a4e66344963)

See #762
Includes the update from #766 

#### Who is reviewing it? 

@TonyMorrison 
@LinkMJB 
@shaundmorris 

#### What are the relevant tickets?

#763 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by AdamBurstynski** [comment]
build now

**Comment by AdamBurstynski** [comment]
build now

**Comment by AdamBurstynski** [comment]
build now

**Comment by shaundmorris** [comment]
merging to improve build structure

**Pull request merged**
