### PR TITLE
CAL-496 added external link icon to external links in docs

### PR DESCRIPTION
**Pull request by ricklarsen**
**PORT to `master` of PR [675](https://github.com/codice/alliance/pull/675)**

#### What does this PR do?

Adds a visual icon to mark external links that take the user away from the Alliance documentation.

(https://github.com/codice/ddf/pull/4053)

#### Who is reviewing it? 
@mcalcote @ahoffer @austinsteffes @garrettfreibott @vinamartin @alexaabrd 

#### Choose 2 committers to review/merge the PR.

@clockard
@lessarderic
@ricklarsen - Documentation
@shaundmorris
@vinamartin

#### How should this be tested?

- builds successfully
- icons added. 

#### What are the relevant tickets?

[CAL-496](https://codice.atlassian.net/browse/CAL-496)
[DDF-4291](https://codice.atlassian.net/browse/DDF-4291)

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by vinamartin** [comment]
screen shot 2018-12-06 at 10 34 11

Manually verified ✅

**Comment by vinamartin** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by ricklarsen** [comment]
previous build failed for missing artifacts from this PR: # [4084](https://github.com/codice/ddf/pull/4084)

**Pull request merged**
