### PR TITLE
CAL-431 Add ResourceRequestByDerivedUri

### PR DESCRIPTION
**Pull request by kcover**
#### What does this PR do?

Changes one line in CatalogInputAdapter to utilize the new ResourceRequestByDerivedUri class in DDF.

#### Who is reviewing it? 

@peterhuffer @emmberk @oconnormi 

#### Choose 2 committers to review/merge the PR.

@clockard
@pklinef

#### How should this be tested?

Verify various types of products ingest and download properly, especially Nitf overviews and originals.

#### What are the relevant tickets?

[CAL-431](https://codice.atlassian.net/browse/CAL-431)
[DDF-3712](https://codice.atlassian.net/browse/DDF-3712)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by oconnormi** [comment]
@kcover is https://github.com/codice/alliance/pull/558/commits/9eb5dbbcbd567ed97140c5923eda23302a3392f7 supposed to be included in this pr?

**Comment by kcover** [comment]
@oconnormi I thought it was but I guess that was just for testing.

**Comment by kcover** [comment]
build now

**Comment by coyotesqrl** [comment]
@kcover Tagging to ask on the status of this PR. Should it be updated and completed so it can be merged, or should it be closed at this time?

**Comment by peterhuffer** [comment]
@coyotesqrl We can temporarily close this. It relies on https://github.com/codice/ddf/pull/3119

**Comment by coyotesqrl** [comment]
Closing for now, as it depends on codice/ddf#3119

**Pull request closed without merging**
