### PR TITLE
CAL-128 Fixed dependency in MgmpTransformer / Fixed itest

### PR DESCRIPTION
**Pull request by bdeining**
#### What does this PR do?
This PR fixes the Alliance build and itests
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@troymohl 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@stustison 
@kcwire
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by jlcsmith** [comment]
👍

**Comment by peterhuffer** [comment]
👍

**Comment by stustison** [comment]
👍

**Comment by jlcsmith** [comment]
Full build successful

**Pull request merged**
