### PR TITLE
CAL-109: Docs fail to build using Oracle JDK on Linux

### PR DESCRIPTION
**Pull request by tbatie**
#### What does this PR do?
Changes dependency version so docs can build on Oracle JDK on Linux
#### Who is reviewing it?
@ricklarsen @shaundmorris @coyotesqrl 
#### How should this be tested?
Docs build successfully 
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
I see that DDF is still using the older versions but docs don't break there. What's the difference between this project and that one?

**Comment by coyotesqrl** [comment]
If @ricklarsen is good with these updates, 👍

**Comment by ricklarsen** [comment]
👍  LGTM

**Comment by shaundmorris** [comment]
👍

**Comment by bcwaters** [comment]
Successfully hero'd
👍

**Comment by jlcsmith** [comment]
👍

**Comment by Beech42** [comment]
I'm trying to do a build on Windows 10 and I can't get docs to build successfully.  Can anyone help?

**Pull request merged**
