### PR TITLE
Run Sonar only on master branch

### PR DESCRIPTION
**Pull request by shaundmorris**
#### What does this PR do?
Runs Sonar only on master branch. The current free tier can only support one branch at a time.
#### Who is reviewing it? 
@TonyMorrison 
@mojogitoverhere 
@Lambeaux 
@andrewzimmer 
@codice/continuous-integration 
@codice/build 

#### How should this be tested?
Build passes

---
This change is [Reviewable](https://reviewable.io/reviews/codice/alliance/888)

### CODE REVIEW

**Comment by shaundmorris** [comment]
build now

**Review by Lambeaux — APPROVED** [review]

**Comment by shaundmorris** [comment]
build now

**Review by TonyMorrison — APPROVED** [review]
Makes sense, looks good

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build passed, but PR status didn't update

**Pull request merged**
