### PR TITLE
CAL-496 added external link icon to external links in docs

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

Adds a visual icon to mark external links that take the user away from the Alliance documentation.

(https://github.com/codice/ddf/pull/4053)

#### Who is reviewing it? 
@mcalcote @ahoffer @austinsteffes @garrettfreibott @vinamartin @alexaabrd 

#### Choose 2 committers to review/merge the PR.

@clockard
@lessarderic
@ricklarsen - Documentation
@shaundmorris
@vinamartin

#### How should this be tested?

- builds successfully
- icons added. 

#### What are the relevant tickets?

[CAL-496](https://codice.atlassian.net/browse/CAL-496)
[DDF-4291](https://codice.atlassian.net/browse/DDF-4291)

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by ricklarsen** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/28/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='Alliance-Jobs/1.1.x/pr/Linux/org.codice.alliance:docs' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/28/org.codice.alliance$docs/testReport'>Alliance-Jobs/1.1.x/pr/Linux/org.codice.alliance:docs</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/28/org.codice.alliance$docs/testReport/alliance.docs/DocumentationTest/testDocumentationIncludes/'><strong>alliance.docs.DocumentationTest.testDocumentationIncludes</strong></a></li></ul>
:x: JOB FAILURE

**Comment by alexaabrd** [comment]
hero successful 🎉

**Pull request merged**
