### PR TITLE
CAL-756 Replaced WaitCondition with Awaitility

### PR DESCRIPTION
**Pull request by AzGoalie**
#### What does this PR do?
Replaced WaitCondition with Awaitility
#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)
#### Choose 2 committers to review/merge the PR.
(please choose ONLY two committers from below, delete the rest)

@brjeter
@pklinef
@shaundmorris

#### What are the relevant tickets?

[CAL-xxx](https://codice.atlassian.net/browse/CAL-xxx)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by AzGoalie** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1139/<h2>Build result: FAILURE</span></h2>[...truncated 1.16 MB...][INFO] ------------------------------------------------------------------------[ERROR] IO Exception: GET request returned a non-200 status code[ERROR] Failed to execute goal org.owasp:dependency-check-maven:3.1.1:check (default) on project video-admin-plugin: Fatal exception(s) analyzing Alliance :: Video :: UI Plugin: Unable to continue dependency-check analysis.[ERROR] Unable to download the NVD CVE data.[ERROR] No documents exist[ERROR] -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] IO Exception: GET request returned a non-200 status code[ERROR] IO Exception: GET request returned a non-200 status code[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionExceptionBuild step 'Invoke top-level Maven targets' marked build as failureNew run name is 'PR 757'Taking single-use slave mesos-jenkins-3d79c664-linux-medium offline.+ echo ERROR: dockerd exited, or diedERROR: dockerd exited, or died+ sleep 5Adding one-line test results to commit status...Setting status of c5819e04417f5fbd43280038b576f6ef79f883b5 to FAILURE with url https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1139/ and message: 'JOB FAILURE: https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1139/ 69 tests run, 0 skipped, 0 failed.'Using context: Internal CI Pipeline
:x: JOB FAILURE

**Comment by AzGoalie** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1140/<h2>Build result: FAILURE</span></h2>[...truncated 1.15 MB...][ERROR] IO Exception: GET request returned a non-200 status code[INFO] ------------------------------------------------------------------------[ERROR] IO Exception: GET request returned a non-200 status code[ERROR] Failed to execute goal org.owasp:dependency-check-maven:3.1.1:check (default) on project video-admin-plugin: Fatal exception(s) analyzing Alliance :: Video :: UI Plugin: Unable to continue dependency-check analysis.[ERROR] Unable to download the NVD CVE data.[ERROR] No documents exist[ERROR] -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] IO Exception: GET request returned a non-200 status code[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionExceptionBuild step 'Invoke top-level Maven targets' marked build as failureNew run name is 'PR 757'Taking single-use slave mesos-jenkins-d1ca29da-linux-medium offline.+ echo ERROR: dockerd exited, or diedERROR: dockerd exited, or died+ sleep 5Adding one-line test results to commit status...Setting status of c5819e04417f5fbd43280038b576f6ef79f883b5 to FAILURE with url https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1140/ and message: 'JOB FAILURE: https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1140/ 69 tests run, 0 skipped, 0 failed.'Using context: Internal CI Pipeline
:x: JOB FAILURE

**Comment by shaundmorris** [comment]
Manually heroed and verified compilations was successful and itests passed. Build failed due to relying on old dependency-check XML feed which will be addressed in a separate PR.

**Pull request merged**
