### PR TITLE
CAL-104 fix embedded dependency not always being embedded

### PR DESCRIPTION
**Pull request by ryeats**
#### What does this PR do?
fix an issue with catalog-core-api-impl not getting embedded when a snapshot was downloaded from nexus
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@adimka @tbatie 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@coyotesqrl
@jlcsmith

#### How should this be tested?
build alliance with a new .m2  mvn clean install -Dmaven.repo.local=/tmp/.m2 then jar -tvf catalog-plugin-defaultsecurityattributevalues.jar and verify two catalog-core-api-impl jars are embedded
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by tbatie** [comment]
http://giphy.com/gifs/vMnuZGHJfFSTe

**Comment by adimka** [comment]
👍 lgtm

**Comment by coyotesqrl** [comment]
:+1:

**Comment by jlcsmith** [comment]
👍

**Pull request merged**
