### PR TITLE
[1.10.x] Remove catalog-async related code

### PR DESCRIPTION
**Pull request by rzwiefel**
#### What does this PR do?
removes code related to the code already removed in DDF

### CODE REVIEW

**Comment by rzwiefel** [comment]
build now .. ?

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now flakey test 😬

**Comment by rzwiefel** [comment]
build now 















I may just remove those tests at this rate

**Comment by rzwiefel** [comment]
To clarify offline discussion: Nitf parsing still exists. There are two plugins- an Asyncronous and synchronous verison. This is only removing the async one which we cannot find in use by any projects currently.

**Comment by jlcsmith** [comment]
Thanks for the clarification @rzwiefel - all good

**Comment by rzwiefel** [comment]
build now pretty please

**Pull request merged**
