### PR TITLE
CAL-190 Update metacard attributes to conform to standard taxonomy naming

### PR DESCRIPTION
**Pull request by mcalcote**
#### What does this PR do? 
Updates the existing nitf imaging attributes to match the expected naming format.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@clockard @peterhuffer @troymohl @dcruver @vinamartin @brianfelix @gordocanchola 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@jlcsmith
@kcwire
@shaundmorris
@lessarderic 

#### How should this be tested?
Inspect the changes to the strings

#### Any background context you want to provide?
A ticket with similar changes is currently under review on the master branch
https://github.com/codice/alliance/pull/192
#### What are the relevant tickets?

[CAL-190](https://codice.atlassian.net/browse/CAL-190)
#### Checklist:
- [ ] Documentation Updated
	- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by mcalcote** [comment]
Hero build passed on 85ba922

**Comment by shaundmorris** [comment]
Do we have adequate unit tests for these metacard attributes?

**Comment by peterhuffer** [comment]
@shaundmorris This is the current coverage https://github.com/codice/alliance/blob/master/catalog/imaging/imaging-transformer-nitf/pom.xml#L169

**Comment by mcalcote** [comment]
There are some tests that check for these exact string values downstream, but they are not specifically checked in these classes. The current test coverage ensures that the attribute helper methods all have non-null values.

**Pull request merged**
