### PR TITLE
CAL-196 Catch all exceptions when parsing MPEG-TS packets

### PR DESCRIPTION
**Pull request by glenhein**
#### What does this PR do?

Catch all exceptions when parsing MPEG-TS packets in order to make streaming video ingestion more resilient.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?

@bdeining 
@jrnorth 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).

@jlcsmith
@lessarderic

#### How should this be tested?

Under a windows vm, stream a long video (200MB+) using ffmpeg. Parsing exceptions will be logged to the DEBUG level. Observe that if an exception is logged, that the processing continues. 

FFMPEG Command: ffmpeg -re -i %1 -map 0 -c copy -f mpegts "udp://127.0.0.1:50000"

Enable logging: log:set DEBUG org.codice.alliance.video.stream.mpegts.netty

#### What are the relevant tickets?

[CAL-196](https://codice.atlassian.net/browse/CAL-196)

#### Checklist:
- [ ] Documentation Updated
	- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by glenhein** [comment]
@lessarderic I'll see if I can create a unit test for it

**Comment by glenhein** [comment]
I added a unit test.

**Comment by jlcsmith** [comment]
I am seeing an itest failure on this.
```
Failed tests:
  testStreamingVideo(org.codice.alliance.test.itests.VideoTest): The parent and child metacards to be created: expectation not met after 15 seconds
```

**Comment by glenhein** [comment]
@jlcsmith just ran all the test, and everything passed:

```[INFO] Reactor Summary:
[INFO] 
[INFO] Alliance ........................................... SUCCESS [  0.349 s]
[INFO] Alliance :: Support ................................ SUCCESS [  0.012 s]
[INFO] Alliance Support Checkstyle ........................ SUCCESS [  0.472 s]
[INFO] Alliance :: Catalog ................................ SUCCESS [  9.064 s]
[INFO] Alliance :: Catalog :: Core ........................ SUCCESS [  0.577 s]
[INFO] Alliance :: Catalog :: Core :: API ................. SUCCESS [  4.761 s]
[INFO] Alliance :: Catalog :: Core :: API Impl ............ SUCCESS [  2.851 s]
[INFO] Alliance :: Catalog :: Core :: MetacardTypes ....... SUCCESS [  2.413 s]
[INFO] Alliance :: Catalog :: Email :: API ................ SUCCESS [  2.020 s]
[INFO] Alliance :: Catalog :: Email :: Impl ............... SUCCESS [  2.818 s]
[INFO] Alliance :: NSILI .................................. SUCCESS [  0.938 s]
[INFO] Alliance :: NSILI :: BQS ........................... SUCCESS [  3.044 s]
[INFO] Alliance :: NSILI :: Common ........................ SUCCESS [  9.381 s]
[INFO] Alliance :: NSILI :: ORB :: API .................... SUCCESS [  2.073 s]
[INFO] Alliance :: NSILI :: ORB :: IMPL ................... SUCCESS [  2.723 s]
[INFO] Alliance :: NSILI :: Input Transformer ............. SUCCESS [  4.082 s]
[INFO] Alliance :: NSILI :: Source ........................ SUCCESS [  6.841 s]
[INFO] Alliance :: NSILI :: Endpoint ...................... SUCCESS [ 12.017 s]
[INFO] Alliance :: NSILI :: UI Plugin ..................... SUCCESS [  9.706 s]
[INFO] Alliance :: NSILI :: App ........................... SUCCESS [  2.303 s]
[INFO] Alliance :: Imaging ................................ SUCCESS [  1.046 s]
[INFO] Alliance :: Imaging :: Service :: API .............. SUCCESS [  1.668 s]
[INFO] Alliance :: Imaging :: Service :: Impl ............. SUCCESS [  3.546 s]
[INFO] Alliance :: Imaging :: Transformer :: Nitf ......... SUCCESS [ 15.773 s]
[INFO] Alliance :: Imaging :: Transformer :: Chipping ..... SUCCESS [  4.386 s]
[INFO] Alliance :: Imaging :: Action Provider :: Chip ..... SUCCESS [  7.974 s]
[INFO] Alliance :: Imaging :: App ......................... SUCCESS [  0.682 s]
[INFO] Alliance :: Catalog :: Plugin ...................... SUCCESS [  0.435 s]
[INFO] Alliance :: Catalog :: Plugin :: Default Security Attribute Value Plugin SUCCESS [  3.726 s]
[INFO] Alliance :: Video .................................. SUCCESS [  0.967 s]
[INFO] Alliance :: Video :: Security ...................... SUCCESS [  3.666 s]
[INFO] Alliance :: Libs ................................... SUCCESS [  0.980 s]
[INFO] Alliance :: STANAG 4609 ............................ SUCCESS [  3.592 s]
[INFO] Alliance :: MPEGTS ................................. SUCCESS [  3.092 s]
[INFO] Alliance :: KLV .................................... SUCCESS [ 13.696 s]
[INFO] Alliance :: Video :: Stream ........................ SUCCESS [  9.515 s]
[INFO] Alliance :: Video :: MPEGTS Transformer ............ SUCCESS [  3.485 s]
[INFO] Alliance :: Video :: UI Plugin ..................... SUCCESS [  9.428 s]
[INFO] Alliance :: Video :: App ........................... SUCCESS [  1.426 s]
[INFO] Alliance :: Security ............................... SUCCESS [  0.347 s]
[INFO] Alliance :: Security :: Banner Markings ............ SUCCESS [  5.181 s]
[INFO] Alliance :: Security :: App ........................ SUCCESS [  0.549 s]
[INFO] Alliance :: Distribution ........................... SUCCESS [  0.738 s]
[INFO] Alliance :: Distribution :: Console Branding ....... SUCCESS [  1.709 s]
[INFO] Alliance :: Distribution :: Branding Plugin ........ SUCCESS [  0.920 s]
[INFO] Alliance :: Distribution :: SDK .................... SUCCESS [  0.357 s]
[INFO] Alliance :: Distribution :: SDK :: Mpegts Stream Generator SUCCESS [  2.267 s]
[INFO] Alliance :: Distribution :: SDK :: Sample NSILI Server SUCCESS [  2.436 s]
[INFO] Alliance :: Distribution :: SDK :: Sample NSILI Client SUCCESS [  2.365 s]
[INFO] Alliance :: SDK :: App ............................. SUCCESS [  0.540 s]
[INFO] Alliance :: Distribution :: Common ................. SUCCESS [  1.237 s]
[INFO] Alliance :: Distribution :: Install Profiles ....... SUCCESS [  0.389 s]
[INFO] Alliance :: Docs ................................... SUCCESS [04:44 min]
[INFO] Alliance :: Distribution :: Alliance ............... SUCCESS [ 57.983 s]
[INFO] Alliance :: Test ................................... SUCCESS [  0.383 s]
[INFO] Alliance :: Test :: Integration Tests .............. SUCCESS [  0.422 s]
[INFO] Alliance :: Test :: Integration :: Common .......... SUCCESS [  4.417 s]
[INFO] Alliance :: Test :: Integration :: Dependencies App  SUCCESS [  2.106 s]
[INFO] Alliance :: Integration :: Test .................... SUCCESS [21:44 min]
[INFO] Alliance :: Libs :: Pom Fix Run .................... SUCCESS [  5.227 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30:48 min
[INFO] Finished at: 2016-12-05T09:31:29-07:00
[INFO] Final Memory: 328M/1670M
[INFO] ------------------------------------------------------------------------
```

**Comment by jlcsmith** [comment]
@glenhein I have not been able to repeat the build failure.

**Pull request merged**
