### PR TITLE
CAL-352 Improve stability of unit tests in StdidcAttributeTest

### PR DESCRIPTION
**Pull request by mackncheesiest**
#### What does this PR do?
It improves stability of unit tests in StdidcAttributeTest

#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)
@adimka @brendan-hofmann 

#### Choose 2 committers to review/merge the PR.
(please choose ONLY two committers from below, delete the rest)
@bdeining
@clockard

#### How should this be tested?
CI build + manual verification that the tests in `catalog/imaging/imaging-transformer-nitf` pass when run with
`mvn clean test`

#### Any background context you want to provide?
The issue arose when, in certain situations, the static field of `StdidcAttribute.FIPS_TO_ISO3_MAP` would be initialized before the setup method is called in `StdidcAttributeTest` and thus before the `karaf.etc` system property was set. As a result, the path to the `fipsToIso.properties` file was not properly defined and the map failed to load.

By moving the system property to be set in the surefire properties, the system property will always be set before any Java code executes -- namely before `StdidcAttribute.FIPS_TO_ISO3_MAP` is initialized.

#### What are the relevant tickets?
[CAL-352](https://codice.atlassian.net/browse/CAL-352)

#### Checklist:
- [ ] Documentation Updated
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by mackncheesiest** [comment]
I don't think the branding plugin has deployed since the version upgrade happened?

**Comment by mackncheesiest** [comment]
build now

**Comment by clockard** [comment]
Local full build passed.

**Pull request merged**
