### PR TITLE
CAL-102 Fixed timezone bug

### PR DESCRIPTION
**Pull request by bdeining**
#### What does this PR do?
This PR fixes a small timezone bug in the MGMP transformer.  Updated the root pom to run unit tests in the UTC timezone.
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@tbatie @glenhein 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@coyotesqrl
@jlcsmith
#### How should this be tested?
Build Alliance
#### Checklist:
- [ ] Documentation Updated
- [X] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
👍

**Comment by glenhein** [comment]
👍

**Comment by jlcsmith** [comment]
👍

**Comment by jrnorth** [comment]
Full build passed. LGTM

**Pull request merged**
