### PR TITLE
CAL-784 removed expired token checks

### PR DESCRIPTION
**Pull request by stustison**
#### What does this PR do?
Removes checks for expired tokens.

#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)
@SmithJosh @bakejeyner 
#### Choose 2 committers to review/merge the PR.
(please choose ONLY two committers from below, delete the rest)

@garrettfreibott 
@blen-desta 
@coyotesqrl 
@pklinef
@stustison
#### What are the relevant tickets?

[CAL-xxx](https://codice.atlassian.net/browse/CAL-xxx)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by shaundmorris** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/RawUdpDataToMTSPacketDecoder.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Codice/alliance/pullRequest?prid=4770370&bid=15898242)

**Comment by shaundmorris** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/RawUdpDataToMTSPacketDecoder.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Codice/alliance/pullRequest?prid=4770370&bid=15898242)

**Comment by stustison** [comment]
build now

**Comment by stustison** [comment]
build now

**Comment by shaundmorris** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/RawUdpDataToMTSPacketDecoder.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Codice/alliance/pullRequest?prid=4770370&bid=15898242)

**Comment by stustison** [comment]
build now

**Comment by shaundmorris** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/RawUdpDataToMTSPacketDecoder.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Codice/alliance/pullRequest?prid=4770370&bid=15898242)

**Comment by shaundmorris** [comment]
build now

Last failure was due to flaky testMultipleTarCompressOrder. See #767

**Comment by shaundmorris** [comment]
Merging to fix build issue

**Pull request merged**
