### PR TITLE
[1.1.x]CAL-506 Update MpegTsInputTransformer to set media type to video/mp2t

### PR DESCRIPTION
**Pull request by brjeter**
#### Who is reviewing it? 
@ahoffer @tyler30clemens @austinsteffes 
#### Choose 2 committers to review/merge the PR.
@emmberk 
@vinamartin
#### How should this be tested?
- Install Alliance.
- `feature:install video-app`
- `catalog:ingest -t mpegts <path-to-mpegts-file>` (https://github.com/codice/alliance/blob/master/catalog/video/video-mpegts-stream/src/test/resources/Closed_Caption_EIA_MPEG2.ts can be used)
- Verify through Intrigue that the media type is `video/mp2t` instead of `application/octet-stream`
#### What are the relevant tickets?

[CAL-506](https://codice.atlassian.net/browse/CAL-506)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [X] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by brjeter** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/35/
:white_check_mark: JOB SUCCESS

**Comment by ahoffer** [comment]
Tested commit 2d8a36. 
A security manager error occured installing the video-app feature. It looks like the install command does not have permission to read files in the etc directory.

After restarting Karaf and manually starting the video transformer bundles, I successfully ingested the test file. The `media.type` attribute was `video/mp2t`. It passed the test per the instructions in the PR.

I'll note that the MIME type in the `metadata` attribute is `application/octect-stream` 

```
[<?xml version="1.0" encoding="UTF-8"?> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
                                <head>                    
                                <meta name="X-Parsed-By" content="org.apache.tika.parser.EmptyParser" /> 
                                <meta name="Content-Type" content="application/octet-stream" /> 
                                <title></title>           
                                </head>                   
                                 /></html>]  
```   

For reference, here is the recommendation of the ACdebugger:

```AC Debugger: Monitoring security exceptions while analyzing missing permissions and doPrivileged() blocks
AC Debugger: Check permission failure for org.apache.karaf.features.command: java.io.FilePermission "${ddf.home.perm}etc${/}DDF_Custom_Mime_Type_Resolver-mpegts.config", "read" {
AC Debugger:     Solution:
AC Debugger:     {
AC Debugger:         Add the following permission block to the appropriate policy file:
AC Debugger:             grant codeBase "file:/org.apache.karaf.features.command" {
AC Debugger:                 permission java.io.FilePermission "${ddf.home.perm}etc${/}DDF_Custom_Mime_Type_Resolver-mpegts.config", "read";
AC Debugger:             }
AC Debugger:     }
AC Debugger: }
[509] /repos/acdebugge```

**Comment by brjeter** [comment]
DDF issue created for the AccessControlException: https://codice.atlassian.net/browse/DDF-4480
Checked with the original user who reported the bug to make sure the `metadata` attribute was not an issue.

**Pull request merged**
