### PR TITLE
CAL-100 Removed alliance prefix from alliance-security-app

### PR DESCRIPTION
**Pull request by bdeining**
#### What does this PR do?
This PR removes the alliance prefix from alliance-security-app to match the app conventions of all other apps within Alliance
#### Who is reviewing it?
@coyotesqrl @jlcsmith @lcrosenbu @jrnorth 
#### How should this be tested?
Build and run Alliance Experimental, observe all apps start
#### What are the relevant tickets?
https://codice.atlassian.net/browse/CAL-100
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
This is fine and won't cause any immediate problems, but without any concept of namespaces I worry that flattening out our feature/app names may cause collisions in the future. In the absence of namespaces, prefixes can provide implicit disambiguation.

**Comment by lcrosenbu** [comment]
Built and tested using clean repo. :+1:

**Comment by jlcsmith** [comment]
LGTM 👍

**Comment by coyotesqrl** [comment]
My comment above about my long-term concern about flattening out namespaces aside, LGTM. 👍

**Pull request merged**
