### PR TITLE
[0.3.x] CAL-356 Updates itests to use embedded solr

### PR DESCRIPTION
**Pull request by vinamartin**
#### What does this PR do?
Updates itests to use embedded solr.
Related to: https://github.com/codice/ddf/pull/2405

#### Who is reviewing it? 
@emanns95 @tbatie 

#### Choose 2 committers to review/merge the PR.
@figliold
@lessarderic

#### How should this be tested?
All itests pass

### CODE REVIEW

**Comment by vinamartin** [comment]
build now

**Comment by vinamartin** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by emanns95** [comment]
I don't think we're going to need this since https://github.com/codice/ddf/pull/2405 should run for test classes extending AbstractIntegrationTest

**Comment by vinamartin** [comment]
Closing out this PR because the comment above

**Pull request closed without merging**
