### PR TITLE
Backport 1.4.x

### PR DESCRIPTION
**Pull request by AdamBurstynski**
#### What does this PR do?

CAL-763 Updated the Jenkinsfile to better match what was happening in the "old style" jobs we used before. (#1) (#762)

Overriding due to failed unit tests and improving the build

(cherry picked from commit babd7916611d5eb21c967387fc767a4e66344963)

See #762
Includes the update from #766 

#### Who is reviewing it? 

@TonyMorrison 
@LinkMJB 
@shaundmorris 

#### What are the relevant tickets?

#763 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by AdamBurstynski** [comment]
build now

**Comment by AdamBurstynski** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/1.4.x/job/pr/job/Linux/1/
:white_check_mark: JOB SUCCESS

**Pull request merged**
