### PR TITLE
CAL-458 update itests to work with external solr

### PR DESCRIPTION
**Pull request by rzwiefel**
#### What does this PR do?
update itests to work with external solr
`anyone`
#### How should this be tested?
running itests

#### What are the relevant tickets?
[CAL-458](https://codice.atlassian.net/browse/CAL-458)

### CODE REVIEW

**Comment by rzwiefel** [comment]
build now

**Comment by mcalcote** [comment]
failed in distribution with `Could not find artifact org.codice.alliance:docs:zip:docs-export:1.2.0-SNAPSHOT`

**Comment by mcalcote** [comment]
Manually verified this change by running the Alliance itest suite.

**Comment by mcalcote** [comment]
build now

**Comment by mcalcote** [comment]
`org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project catalog-nsili-common: Could not resolve dependencies for project org.codice.alliance.nsili:catalog-nsili-common:jar:1.2.0-SNAPSHOT: Could not transfer artifact org.geotools.xsd:gt-xsd-gml3:jar:19.1`

**Comment by mcalcote** [comment]
build now

**Comment by rzwiefel** [comment]
✅

**Pull request merged**
