### PR TITLE
CAL-784 updated to work with the STS and IdP removal

### PR DESCRIPTION
**Pull request by stustison**
#### What does this PR do?
Just updates to use with DDF master
#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)
#### Choose 2 committers to review/merge the PR.
(please choose ONLY two committers from below, delete the rest)

@shaundmorris
@stustison

#### How should this be tested?
Run full build.
#### What are the relevant tickets?

[CAL-xxx](https://codice.atlassian.net/browse/CAL-xxx)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by shaundmorris** [comment]
build now

**Comment by stustison** [comment]
build now

**Comment by shaundmorris** [comment]
build now 

Previous build had strange error messages trying to run itests and aborted for some reason.

**Comment by shaundmorris** [comment]
The build was a success but the status on the PR didn't update. Will address that separately and merge this PR to fix a build issue.

**Pull request merged**
