### PR TITLE
CAL-41 Provide the ability to drape NITF overviews on the map

### PR DESCRIPTION
**Pull request by jrnorth**
#### What does this PR do?
Adds the ability to drape NITF overviews on the Cesium and OpenLayers maps.

This PR different from https://github.com/codice/ddf/pull/699 in that it only exposes the NITF overview as an overlayable image. It doesn't create any new UI components, action providers, or metacard transformers, as those were developed in the DDF ticket.

#### Who is reviewing it?
@glenhein 
@dcruver 
@kcwire 
@jlcsmith 

#### How should this be tested?
Ingest some NITFs. Go to the Search UI and search for them. Verify that each NITF with an overview image has a Map Action called `Overlay overview on the map`, and that when it is clicked, the overview image is overlaid on the map.

#### What are the relevant tickets?
[CAL-41](https://codice.atlassian.net/browse/CAL-41)

#### Screenshots (if appropriate)
See CAL-41

#### Checklist:
- [ ] Documentation Updated
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by bdeining** [comment]
There's a PR in review right now that puts a max pixel limit for NITF overview images to 1024.  Is this going to effect image draping? @dcruver can correct me if I am wrong, but if this is an issue, the full sized image is still available with the `original` qualifier.

**Comment by jrnorth** [comment]
It won't be an issue. The full-size images were making the map a bit slow when you draped them anyway.

**Comment by bdeining** [comment]
:+1:

**Comment by jlcsmith** [comment]
needs a rebase please

**Comment by jlcsmith** [comment]
@jrnorth - I'm seeing the imaging app fail to deploy due to `org.osgi.service.blueprint.container.ComponentDefinitionException: org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to load class org.codice.alliance.transformer.nitf.OverviewSupplier from recipe BeanRecipe[name='#recipe-89']`

**Comment by jlcsmith** [comment]
Built and tested.  Other than the existing bug related to the image not aligning with the image polygon on the map, this LGTM.  👍

**Comment by jaymcnallie** [comment]
LGTM 👍

**Pull request merged**
