### PR TITLE
CAL-291 fixed typo in dependency list docs

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

fixes incorrect document type in dependency list docs. 

#### Who is reviewing it? 

@ahoffer @bakejeyner @blen-desta @garrettfreibott 

#### Choose 2 committers to review/merge the PR.
@clockard
@lessarderic
@ricklarsen - Documentation
@shaundmorris

#### How should this be tested?
builds successfully with dependency list included. 

#### What are the relevant tickets?

[CAL-291](https://codice.atlassian.net/browse/CAL-291)

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by ricklarsen** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/38/<h2>Build result: FAILURE</span></h2>[...truncated 1.41 MB...][INFO] Finished at: 2019-02-26T18:07:20+00:00[INFO] Final Memory: 56M/895M[INFO] ------------------------------------------------------------------------[ERROR] Failed to execute goal org.owasp:dependency-check-maven:3.0.2:check (default) on project imaging-actionprovider-chip: One or more exceptions occurred during dependency-check analysis: One or more exceptions occurred during dependency-check analysis[ERROR] The download was interrupted; unable to complete the update[ERROR] -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionExceptionBuild step 'Invoke top-level Maven targets' marked build as failureSet build name.New build name is 'PR 701'Taking single-use slave mesos-jenkins-09d8c86fdafb40788c1b5c278603424a-linux-medium offline.[BFA] Scanning build for known causes...[BFA] Found failure cause(s):[BFA] OWASP NVD CVE data download failure from category network,[BFA] Done. 2sAdding one-line test results to commit status...Setting status of 2feb00f74628a864825add704277a64759a021d2 to FAILURE with url https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/38/ and message: 'JOB FAILURE: https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/38/ 70 tests run, 0 skipped, 0 failed.'Using context: Internal CI Pipeline
:x: JOB FAILURE

**Comment by ricklarsen** [comment]
rerunning build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/39/<h2>Build result: FAILURE</span></h2>[...truncated 1.41 MB...][ERROR] [ERROR] See the dependency-check report for more details.[ERROR] -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException[ERROR] [ERROR] After correcting the problems, you can resume the build with the command[ERROR]   mvn <goals> -rf :imaging-appBuild step 'Invoke top-level Maven targets' marked build as failureSet build name.New build name is 'PR 701'Taking single-use slave mesos-jenkins-763157440fdf450db85a539a1d94c439-linux-medium offline.[BFA] Scanning build for known causes...[BFA] Found failure cause(s):[BFA] OWASP CVSS score from category OWASP[BFA] Done. 2sAdding one-line test results to commit status...Setting status of 2feb00f74628a864825add704277a64759a021d2 to FAILURE with url https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/39/ and message: 'JOB FAILURE: https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/39/ 70 tests run, 0 skipped, 0 failed.'Using context: Internal CI Pipeline
:x: JOB FAILURE

**Comment by ricklarsen** [comment]
updated dependency check config. 
rerun build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/40/
:white_check_mark: JOB SUCCESS

**Pull request merged**
