### PR TITLE
CAL-505 removed Coverity stage from Jenkinsfile

### PR DESCRIPTION
**Pull request by shaundmorris**
#### What does this PR do?
Remove Coverity stage from the Jenkins file
#### Who is reviewing it? 
@codice/build 
@LinkMJB 
@rymach

#### Choose 2 committers to review/merge the PR.
(please choose ONLY two committers from below, delete the rest)
@jrnorth 
@vinamartin
@oconnormi 
#### How should this be tested?
Verification of the syntax on the build file should be sufficient
#### Any background context you want to provide?
We haven't been able to build with Coverity in about a year
#### What are the relevant tickets?
[CAL-505](https://codice.atlassian.net/browse/CAL-505)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

---
This change is [Reviewable](https://reviewable.io/reviews/codice/alliance/694)

### CODE REVIEW

**Comment by shaundmorris** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1058/<h2>Build result: FAILURE</span></h2>[...truncated 1.05 MB...][BFA] Found failed test case: testSingleTarCompressOrder[BFA] Found failed test case: testMultipleFilesGZipOrder[BFA] Found failed test case: testUnsetOutputName[BFA] Found failed test case: testSingleFilesGZipOrder[BFA] Found failed test case: testMultipleTarZipOrder[BFA] Found failed test case: testMultipleFilesZipOrder[BFA] Found failed test case: testSingleCompressedOrder[BFA] Found failed test case: testMultipleTarUncompressedOrder[BFA] Found failed test case: testMultipleUncompressedOrder[BFA] Found failed test case: testSingleFilesZipOrder[BFA] Found failed test case: testNoProduct[BFA] Found failed test case: testSetUserInfo[BFA] Found failed test case: testSingleUncompressedOrder[BFA] Found failed test case: getRemainingDelay[BFA] Found failed test case: testSingleTarGZipOrder[BFA] Found failed test case: testCancel[BFA] Found failed test case: testGetStatus[BFA] Found failed test case: testNoPSpec[BFA] Found failed test case: testUnsetDestName[BFA] Found failed test case: testSupportedEmailDeliveryAdding one-line test results to commit status...Setting status of d3b94bd4a2f4b184a72f7dd0a2c80e973e8abe60 to FAILURE with url https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1058/ and message: 'JOB FAILURE: https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1058/ 280 tests run, 0 skipped, 183 failed.'Using context: Internal CI Pipeline
:x: JOB FAILURE

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1059/<h2>Build result: FAILURE</span></h2>[...truncated 1.05 MB...][BFA] Found failed test case: testSingleTarCompressOrder[BFA] Found failed test case: testMultipleFilesGZipOrder[BFA] Found failed test case: testUnsetOutputName[BFA] Found failed test case: testSingleFilesGZipOrder[BFA] Found failed test case: testMultipleTarZipOrder[BFA] Found failed test case: testMultipleFilesZipOrder[BFA] Found failed test case: testSingleCompressedOrder[BFA] Found failed test case: testMultipleTarUncompressedOrder[BFA] Found failed test case: testMultipleUncompressedOrder[BFA] Found failed test case: testSingleFilesZipOrder[BFA] Found failed test case: testNoProduct[BFA] Found failed test case: testSetUserInfo[BFA] Found failed test case: testSingleUncompressedOrder[BFA] Found failed test case: getRemainingDelay[BFA] Found failed test case: testSingleTarGZipOrder[BFA] Found failed test case: testCancel[BFA] Found failed test case: testGetStatus[BFA] Found failed test case: testNoPSpec[BFA] Found failed test case: testUnsetDestName[BFA] Found failed test case: testSupportedEmailDeliveryAdding one-line test results to commit status...Setting status of d3b94bd4a2f4b184a72f7dd0a2c80e973e8abe60 to FAILURE with url https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1059/ and message: 'JOB FAILURE: https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1059/ 280 tests run, 0 skipped, 183 failed.'Using context: Internal CI Pipeline
:x: JOB FAILURE

**Comment by shaundmorris** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1061/
:white_check_mark: JOB SUCCESS

**Pull request merged**
