### PR TITLE
CAL-278 updated jbake.properties for transformers template

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?
- updates `jbake.properties` to use the transformers template added to DDF in https://github.com/codice/ddf/pull/1954. 

#### Who is reviewing it?

@mcalcote @vinamartin @Lambeaux @jrnorth 

#### Choose 2 committers to review/merge the PR.

@coyotesqrl
@jlcsmith
@lessarderic
@pklinef
@shaundmorris

#### How should this be tested?

verify all sections being included in `jdocumentation.pdf` (attached).

#### What are the relevant tickets?

[CAL-278](https://codice.atlassian.net/browse/CAL-278)
[DDF-2888](https://codices.atlassian.net/browse/DDF-2888)

#### Screenshots (if appropriate)

[jdocumentation.pdf](https://github.com/codice/alliance/files/972139/jdocumentation.pdf)

#### Checklist:
- [x] Documentation Updated
	- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Comment by clockard** [comment]
Jenkins build passed but was getting hung up on clean up

**Pull request merged**
