### PR TITLE
[1.1.x] CAL-473 - Port of test dependency changes from master 

### PR DESCRIPTION
**Pull request by paouelle**
Link to master PRs: #649 and #676 

#### What does this PR do?
It relocates various generic test and maven utilities to codice-test and codice-maven repositories.

#### Who is reviewing it? 
@AzGoalie
@figliold
@tbatie
@peterhuffer 

#### Choose 2 committers to review/merge the PR.
@coyotesqrl
@lessarderic
@clockard 

#### How should this be tested?
successful PR build should be sufficient

#### What are the relevant tickets?
[CAL-473](https://codice.atlassian.net/browse/CAL-473)
[CAL-498](https://codice.atlassian.net/browse/CAL-498)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by paouelle** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/33/<h2>Build result: FAILURE</span></h2>[...truncated 1.94 MB...][ERROR] [ERROR] See the dependency-check report for more details.[ERROR] -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException[ERROR] [ERROR] After correcting the problems, you can resume the build with the command[ERROR]   mvn <goals> -rf :catalog-nsili-commonBuild step 'Invoke top-level Maven targets' marked build as failureSet build name.New build name is 'PR 690'Taking single-use slave mesos-jenkins-72e25ff755c04481a6815ec32dba5f90-linux-medium offline.[BFA] Scanning build for known causes...[BFA] Found failure cause(s):[BFA] OWASP CVSS score from category OWASP[BFA] Done. 2sAdding one-line test results to commit status...Setting status of cc2d1e978f413455be02357b6b8c80aba62b6a09 to FAILURE with url https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/33/ and message: 'JOB FAILURE: https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/33/ 1557 tests run, 1 skipped, 0 failed.'Using context: Internal CI Pipeline
:x: JOB FAILURE

**Comment by paouelle** [comment]
build now

CVE was fixed in DDF last night

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/1.1.x/job/pr/job/Linux/34/
:white_check_mark: JOB SUCCESS

**Pull request merged**
