### PR TITLE
BR-42 Upgrade Maven version

### PR DESCRIPTION
**Pull request by TonyMorrison**
#### What does this PR do?
Upgraded the version of Maven to 'maven-latest' in the Jenkinsfile. Accordingly the pom was modified, with the ddf-parent upgraded to 1.0.10, and codice-maven to 0.3

Also added using an image pre-loaded with .m2 dependency cache and error trapping for cleanup routine at the end 

#### Who is reviewing it? 
@shaundmorris 
@LinkMJB 
@paouelle 

#### Choose 2 committers to review/merge the PR.
@bdeining
@shaundmorris

#### How should this be tested?
http://jenkins.phx.connexta.com/service/jenkins/job/W.I.P./job/alliance_TM/job/master/

#### What are the relevant tickets?
BR-42 Upgrade Maven version
https://octoconsulting.atlassian.net/jira/software/projects/BR/boards/47?selectedIssue=BR-42

### CODE REVIEW

**Comment by shaundmorris** [comment]
build now

**Comment by TonyMorrison** [comment]
build now

**Comment by shaundmorris** [comment]
build now

We may have to try merging this since we are hitting the 1 hour time limit on incremental build.

**Comment by TonyMorrison** [comment]
build now

**Comment by TonyMorrison** [comment]
build now

**Pull request merged**
