### PR TITLE
CAL-343 Added Version.txt to the distribution

### PR DESCRIPTION
**Pull request by emmberk**
#### What does this PR do?
This PR fixes an issue that was causing Alliance itests to fail.
#### Who is reviewing it? 
@mackncheesiest @vinamartin @mcalcote @paouelle 
#### Choose 2 committers to review/merge the PR.
@bdeining
@clockard
#### How should this be tested?
Itests.
#### Any background context you want to provide?
DDF Platform Migration requires a Version.txt file to be in <distribution_home>: https://github.com/codice/ddf/blob/dd74349c3f2260e96d74ee8a2c0383dff35c5ab0/platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java#L100-L102.
#### What are the relevant tickets?
[CAL-343](https://codice.atlassian.net/browse/CAL-343)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by emmberk** [comment]
I successfully completed the itests locally:+1:

**Comment by clockard** [comment]
build now

**Comment by bdeining** [comment]
full build successful 👍

**Pull request merged**
