### PR TITLE
CAL-291 reorganized docs content directories to align with outline

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

reorders the directory structure of the docs content to map to the primary documentation outline for ease of maintainability.

#### Who is reviewing it? 
@mcalcote @ahoffer @austinsteffes @garrettfreibott @emmberk 

#### Ask 2 committers to review/merge the PR and tag them here.

@clockard
@lessarderic
@shaundmorris

#### How should this be tested?

builds successfully; no changes made to content
(will need manual confirmation of build on Windows)

#### What are the relevant tickets?
[DDF-4091](https://codice.atlassian.net/browse/DDF-4091)
[CAL-291](https://codice.atlassian.net/browse/CAL-291

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by ricklarsen** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/<h2>Failed Tests: <span class='status-failure'>36</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance</a>: <span class='status-failure'>36</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testInvalidMarkings/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testInvalidMarkings</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleWordDoc/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleWordDoc</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testBannerMarkingMismatch/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testBannerMarkingMismatch</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleText/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleText</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingCodewordsAndDissem/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingCodewordsAndDissem</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testCosmicMarkingSimplePdf/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testCosmicMarkingSimplePdf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfWithoutImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfWithoutImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationJpeg/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationJpeg</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationNitf/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationNitf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidMtiNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidMtiNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidImageNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidImageNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGenerationThumbnailOnly/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGenerationThumbnailOnly</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p001a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p001a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p002a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p002a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p004b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p004b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p009a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p009a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p010b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p010b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p012a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p012a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p014b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p014b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p016a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p016a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p102b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p102b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p104a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p104a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p106b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p106b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p011xa/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p011xa</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testSubmitQuery/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testSubmitQuery</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrViaCallback/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrViaCallback</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrGetHitCount/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrGetHitCount</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testStandingQueryMgr/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testStandingQueryMgr</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/999/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/VideoTest/testStreamingVideo/'><strong>org.codice.alliance.test.itests.VideoTest.testStreamingVideo</strong></a></li></ul>
:x: JOB FAILURE

**Comment by ricklarsen** [comment]
updated to rerun build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/<h2>Failed Tests: <span class='status-failure'>36</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance</a>: <span class='status-failure'>36</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testInvalidMarkings/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testInvalidMarkings</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleWordDoc/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleWordDoc</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testBannerMarkingMismatch/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testBannerMarkingMismatch</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleText/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleText</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingCodewordsAndDissem/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingCodewordsAndDissem</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testCosmicMarkingSimplePdf/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testCosmicMarkingSimplePdf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfWithoutImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfWithoutImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationJpeg/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationJpeg</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationNitf/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationNitf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidMtiNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidMtiNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidImageNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidImageNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGenerationThumbnailOnly/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGenerationThumbnailOnly</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p001a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p001a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p002a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p002a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p004b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p004b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p009a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p009a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p010b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p010b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p012a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p012a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p014b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p014b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p016a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p016a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p102b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p102b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p104a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p104a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p106b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p106b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p011xa/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p011xa</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testSubmitQuery/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testSubmitQuery</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrViaCallback/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrViaCallback</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrGetHitCount/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrGetHitCount</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testStandingQueryMgr/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testStandingQueryMgr</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1001/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/VideoTest/testStreamingVideo/'><strong>org.codice.alliance.test.itests.VideoTest.testStreamingVideo</strong></a></li></ul>
:x: JOB FAILURE

**Comment by ricklarsen** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1005/
:white_check_mark: JOB SUCCESS

**Pull request merged**
