### PR TITLE
DDF-04481 Removed realm support from the Web Context Policy Manager

### PR DESCRIPTION
**Pull request by blen-desta**
#### What does this PR do?
Fixes alliance issues that will arise from the removal of realms from the Web Context Policy Manager by https://github.com/codice/ddf/pull/4620

#### Who is reviewing it? 
@bakejeyner 

#### Choose 2 committers to review/merge the PR.
@garrettfreibott 
@stustison

#### How should this be tested?
Test that everything still works as expected.

#### Any background context you want to provide?
See: https://github.com/codice/ddf/pull/4620

#### What are the relevant tickets?
For GH Issues:
Fixes: https://github.com/codice/ddf/issues/4481

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by bakejeyner** [comment]
Cumulative hero successful ✔️

**Comment by stustison** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/<h2>Failed Tests: <span class='status-failure'>32</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance</a>: <span class='status-failure'>32</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/org_codice_alliance_test_itests_BannerMarkingsTest/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.org.codice.alliance.test.itests.BannerMarkingsTest</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfWithoutImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfWithoutImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationJpeg/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationJpeg</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationNitf/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationNitf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidMtiNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidMtiNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidImageNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidImageNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGenerationThumbnailOnly/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGenerationThumbnailOnly</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p001a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p001a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p002a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p002a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p004b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p004b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p009a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p009a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p010b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p010b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p012a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p012a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p014b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p014b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p016a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p016a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p102b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p102b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p104a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p104a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p106b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p106b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p011xa/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p011xa</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testSubmitQuery/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testSubmitQuery</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrViaCallback/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrViaCallback</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrGetHitCount/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrGetHitCount</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testStandingQueryMgr/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testStandingQueryMgr</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/VideoTest/testStreamingVideo/'><strong>org.codice.alliance.test.itests.VideoTest.testStreamingVideo</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1075/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ContainerPerSuiteItestSuite/org_codice_alliance_test_itests_ContainerPerSuiteItestSuite/'><strong>org.codice.alliance.test.itests.ContainerPerSuiteItestSuite.org.codice.alliance.test.itests.ContainerPerSuiteItestSuite</strong></a></li></ul>
:x: JOB FAILURE

**Comment by blen-desta** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1076/<h2>Failed Tests: <span class='status-failure'>2</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1076/org.codice.alliance.test.itests$test-itests-alliance/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance</a>: <span class='status-failure'>2</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1076/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1076/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceAvailable</strong></a></li></ul>
:x: JOB FAILURE

**Comment by blen-desta** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1077/
:white_check_mark: JOB SUCCESS

**Pull request merged**
