### PR TITLE
Updated development version

### PR DESCRIPTION
**Pull request by bdeining**
#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)
#### Choose 2 committers to review/merge the PR.
(please choose ONLY two committers from below, delete the rest)

@andrewkfiedler
@bdeining
@beyelerb
@brendan-hofmann
@brjeter
@clockard
@coyotesqrl
@figliold
@jaymcnallie
@jlcsmith
@kcwire
@lessarderic
@michaelmenousek
@millerw8
@mrmateo
@pklinef
@ricklarsen - Documentation
@rzwiefel
@shaundmorris
@stustison
@tbatie
@vinamartin
#### What are the relevant tickets?

[CAL-xxx](https://codice.atlassian.net/browse/CAL-xxx)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1131/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance.nsili:catalog-nsili-endpoint' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1131/org.codice.alliance.nsili$catalog-nsili-endpoint/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance.nsili:catalog-nsili-endpoint</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1131/org.codice.alliance.nsili$catalog-nsili-endpoint/testReport/org.codice.alliance.nsili.endpoint.requests/OrderRequestImplTest/testMultipleTarCompressOrder/'><strong>org.codice.alliance.nsili.endpoint.requests.OrderRequestImplTest.testMultipleTarCompressOrder</strong></a></li></ul>
:x: JOB FAILURE

**Comment by bdeining** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1132/<h2>Build result: FAILURE</span></h2>[...truncated 1.94 MB...][INFO] Finished at: 2019-10-22T18:31:28+00:00[ERROR] IO Exception: GET request returned a non-200 status code[ERROR] IO Exception: GET request returned a non-200 status code[ERROR] IO Exception: GET request returned a non-200 status code[ERROR] IO Exception: GET request returned a non-200 status code[INFO] Final Memory: 40M/154M[INFO] ------------------------------------------------------------------------[ERROR] Failed to execute goal org.owasp:dependency-check-maven:3.1.1:check (default) on project alliance: Fatal exception(s) analyzing Alliance: Unable to continue dependency-check analysis.[ERROR] Unable to download the NVD CVE data.[ERROR] No documents exist[ERROR] -> [Help 1][ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.[ERROR] Re-run Maven using the -X switch to enable full debug logging.[ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionExceptionBuild step 'Invoke top-level Maven targets' marked build as failureNew run name is 'PR 751'Taking single-use slave mesos-jenkins-b4985df2-linux-medium offline.Adding one-line test results to commit status...Setting status of a8d5903803308fe59446d8e27e6e6dff9e5ff1d3 to FAILURE with url https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1132/ and message: 'JOB FAILURE: https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1132/ 1580 tests run, 0 skipped, 0 failed.'Using context: Internal CI Pipeline
:x: JOB FAILURE

**Pull request merged**
