### PR TITLE
CAL-417 Upgraded to Jacoco 0.8.0

### PR DESCRIPTION
**Pull request by shaundmorris**
#### What does this PR do?
Upgrade to Jacoco 0.8.0
#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)
@codice/build 
@codice/test 
#### Choose 2 committers to review/merge the PR.
(please choose ONLY two committers from below, delete the rest)
@bdeining
@clockard
@lessarderic 
#### How should this be tested?
Successful build on Windows and Linux
#### What are the relevant tickets?

[CAL-417](https://codice.atlassian.net/browse/CAL-417)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

---
This change is [Reviewable](https://reviewable.io/reviews/codice/alliance/538)

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
The previous build failures was due to a unrelated artifact failing to be transferred. `Could not transfer artifact org.codice.webjars:pnotify:jar:1.3.1 from/to office`

**Comment by shaundmorris** [comment]
Second build failure unrelated: `Could not transfer artifact org.antlr:antlr4:jar:4.5.1-1 from/to office`

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
Third build failure unrelated: `Could not transfer artifact ddf.catalog.opensearch:catalog-opensearch-source:jar:2.12.0-20180217.062453-127 from/to office`

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by LinkMJB** [comment]
Testing a potential network tuning fix

build now

**Pull request merged**
