### PR TITLE
CAL-455 Removed redundant pom properties

### PR DESCRIPTION
**Pull request by mcalcote**
#### What does this PR do?
Added Codice-Parent as the parent project to Alliance. Removed pom properties that are also defined in the Codice-Parent pom. Also adjusted poms to utilize property replacement where possible. Some minor pre-existing pom issues cleaned up as well.

#### Who is reviewing it? 
@garrettfreibott @austinsteffes @ahoffer @ricklarsen @shaundmorris @pklinef @clockard @djblue @lessarderic @coyotesqrl

#### How should this be tested?
Build, install and run to ensure compilation and runtime dependencies are satisfied. 

#### Any background context you want to provide?
This is part of an effort to move dependency management to a centralized location. We will need to evaluate dependencies that are using other versions that what is specified in the parent pom and justify or update them as needed. 

#### What are the relevant tickets?
[CAL-455](https://codice.atlassian.net/browse/CAL-455)
These changes are dependent on the following PR:
https://github.com/codice/codice-parent/pull/2
Related to:
https://github.com/codice/ddf/pull/3730

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by mcalcote** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/<h2>Failed Tests: <span class='status-failure'>36</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance</a>: <span class='status-failure'>36</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testInvalidMarkings/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testInvalidMarkings</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleWordDoc/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleWordDoc</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testBannerMarkingMismatch/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testBannerMarkingMismatch</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleText/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleText</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingCodewordsAndDissem/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingCodewordsAndDissem</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testCosmicMarkingSimplePdf/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testCosmicMarkingSimplePdf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfWithoutImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfWithoutImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationJpeg/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationJpeg</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationNitf/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationNitf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidMtiNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidMtiNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidImageNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidImageNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGenerationThumbnailOnly/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGenerationThumbnailOnly</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p001a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p001a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p002a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p002a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p004b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p004b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p009a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p009a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p010b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p010b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p012a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p012a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p014b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p014b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p016a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p016a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p102b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p102b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p104a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p104a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p106b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p106b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p011xa/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p011xa</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testSubmitQuery/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testSubmitQuery</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrViaCallback/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrViaCallback</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrGetHitCount/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrGetHitCount</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testStandingQueryMgr/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testStandingQueryMgr</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1008/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/VideoTest/testStreamingVideo/'><strong>org.codice.alliance.test.itests.VideoTest.testStreamingVideo</strong></a></li></ul>
:x: JOB FAILURE

**Comment by mcalcote** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/<h2>Failed Tests: <span class='status-failure'>36</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance.test.itests:test-itests-alliance</a>: <span class='status-failure'>36</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testInvalidMarkings/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testInvalidMarkings</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleWordDoc/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleWordDoc</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testBannerMarkingMismatch/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testBannerMarkingMismatch</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingSimpleText/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingSimpleText</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testUsMarkingCodewordsAndDissem/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testUsMarkingCodewordsAndDissem</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/BannerMarkingsTest/testCosmicMarkingSimplePdf/'><strong>org.codice.alliance.test.itests.BannerMarkingsTest.testCosmicMarkingSimplePdf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfWithoutImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfWithoutImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGeneration/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGeneration</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationJpeg/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationJpeg</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testImageNitfChipCreationNitf/'><strong>org.codice.alliance.test.itests.ImagingTest.testImageNitfChipCreationNitf</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidMtiNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidMtiNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testValidImageNitfMetacard/'><strong>org.codice.alliance.test.itests.ImagingTest.testValidImageNitfMetacard</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfImageGenerationThumbnailOnly/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfImageGenerationThumbnailOnly</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p001a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p001a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p002a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p002a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p004b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p004b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p009a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p009a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p010b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p010b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p012a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p012a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p014b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p014b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p016a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p016a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p102b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p102b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p104a/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p104a</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p106b/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p106b</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/ImagingTest/testNitfJpeg2000p011xa/'><strong>org.codice.alliance.test.itests.ImagingTest.testNitfJpeg2000p011xa</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testSubmitQuery/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testSubmitQuery</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrViaCallback/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrViaCallback</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testCatalogMgrGetHitCount/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testCatalogMgrGetHitCount</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliEndpointTest/testStandingQueryMgr/'><strong>org.codice.alliance.test.itests.NsiliEndpointTest.testStandingQueryMgr</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchGetAll/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchGetAll</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceAvailable/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceAvailable</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliHttpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliHttpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/NsiliSourceTest/testNsiliFtpSourceOpenSearchLocation/'><strong>org.codice.alliance.test.itests.NsiliSourceTest.testNsiliFtpSourceOpenSearchLocation</strong></a></li><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1009/org.codice.alliance.test.itests$test-itests-alliance/testReport/org.codice.alliance.test.itests/VideoTest/testStreamingVideo/'><strong>org.codice.alliance.test.itests.VideoTest.testStreamingVideo</strong></a></li></ul>
:x: JOB FAILURE

**Comment by mcalcote** [comment]
Itests were failing because the errorprone package was being imported in catalog-nsili-source. build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1011/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance:docs' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1011/org.codice.alliance$docs/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance:docs</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1011/org.codice.alliance$docs/testReport/alliance.docs/DocumentationTest/testBrokenAnchorsPresent/'><strong>alliance.docs.DocumentationTest.testBrokenAnchorsPresent</strong></a></li></ul>
:x: JOB FAILURE

**Comment by mcalcote** [comment]
build now

**Comment by cxbot1** [comment]
Internal build has been scheduled, your results will be available at build completion.

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1012/<h2>Failed Tests: <span class='status-failure'>1</span></h2><h3><a name='Alliance-Jobs/pr/Linux/org.codice.alliance:docs' /><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1012/org.codice.alliance$docs/testReport'>Alliance-Jobs/pr/Linux/org.codice.alliance:docs</a>: <span class='status-failure'>1</span></h3><ul><li><a href='https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1012/org.codice.alliance$docs/testReport/alliance.docs/DocumentationTest/testBrokenAnchorsPresent/'><strong>alliance.docs.DocumentationTest.testBrokenAnchorsPresent</strong></a></li></ul>
:x: JOB FAILURE

**Comment by mcalcote** [comment]
build now

**Comment by cxbot1** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.codice.org/job/Alliance-Jobs/job/pr/job/Linux/1013/
:white_check_mark: JOB SUCCESS

**Pull request merged**
