### PR TITLE
CAL-147  Removed Alliance app and MGMP transformers

### PR DESCRIPTION
**Pull request by jlcsmith**
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?

@bdeining @lcrosenbu 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).

@kcwire 
#### Checklist:
- [X] Documentation Updated
- [X] Update / Add Unit Tests
- [X] Update / Add Integration Tests

### CODE REVIEW

**Comment by bdeining** [comment]
Hero Build Successful and apps start successfully.  👍

**Comment by kcwire** [comment]
@jlcsmith can you rebase this so we can merge it?

**Comment by bdeining** [comment]
@jlcsmith  @kcwire rebased

**Comment by bdeining** [comment]
swarm build successful, verified that the Alliance app is gone and that the system starts up correctly 👍

**Comment by jlcsmith** [comment]
👍

**Pull request merged**
