### PR TITLE
Remove catalog-async related code(cherrypick)

### PR DESCRIPTION
**Pull request by rzwiefel**
#### What does this PR do?
Remove catalog-async related code

### CODE REVIEW

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
Build now

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by vinamartin** [comment]
Did a full build locally, overriding CI.

**Pull request merged**
