### PR TITLE
Update to a DDF 2.26 nightly build version

### PR DESCRIPTION
**Pull request by shaundmorris**
#### What does this PR do?
Upgrades to DDF 2.26.0-SNAPSHOT
Currently 1.13 depends on a DDF 2.25.x version
#### Who is reviewing it? 
@LinkMJB 
@AdamBurstynski 
@TonyMorrison 

#### Choose 2 committers to review/merge the PR.
(please choose ONLY two committers from below, delete the rest)
@jlcsmith 
@pklinef 

#### How should this be tested?
Passing build
Might need a manual hero to make sure alliance comes up and installs correctly
#### Any background context you want to provide?
Looking to test latest DDF and Alliance

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

---
This change is [Reviewable](https://reviewable.io/reviews/codice/alliance/834)

### CODE REVIEW

**Review by jlcsmith — APPROVED** [review]

**Comment by jlcsmith** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
Closing since the DDF 2.26.0 upgrade on this PR will make this PR OBE. https://github.com/codice/alliance/pull/858

**Pull request closed without merging**
