### PR TITLE
MPEG-TS Streaming Fixes

### PR DESCRIPTION
**Pull request by jrnorth**
#### What does this PR do?
- Fix MPEG-TS UDP streaming
  - The stream startup code had been erroneously replaced with the stream shutdown code.
  - The videographer user needs the 'guest' role to create metacards.
- Update location and frame center updaters to handle GeometryCollections
- Fix thread interrupt handling
- Fix and re-enable VideoTest
- Delete unused metacard updaters

#### Who is reviewing it?
@sgalla 
@aj-brooks 

#### Choose 2 committers to review/merge the PR.
@blen-desta 
@glenhein 

#### How should this be tested?
1. Install Alliance with the video app.
2. Configure a video stream in the Admin UI. The default settings will work fine, but you can change the title or filename template if you want.
3. Stream an MPEG-TS video to the address specified in the stream configuration from the previous step (the default is `127.0.0.1:50000`). Two sample videos are available here: https://samples.ffmpeg.org/MPEG2/mpegts-klv/
a. Using [FFmpeg](https://ffmpeg.org/): `ffmpeg -re -i Night_Flight_IR.mpg -map 0 -c copy -f mpegts udp://127.0.0.1:50000`
b. Using [TSduck](https://tsduck.io/): `tsp -I file Night_Flight_IR.mpg -P regulate -O ip 127.0.0.1:50000`
4. Wait for the video to finish streaming.
5. Open Intrigue and search for the stream title (for the parent metacard) and the filename template (for the chunks). Verify the parent metacard has a location and/or a frame center geometry. Verify the chunk metacards also have locations and/or frame center geometries.

#### Any background context you want to provide?
MPEG-TS UDP streaming has been broken since 1.4.0 due to [this change](https://github.com/codice/alliance/commit/b2200d94aaefd0239b3c1f2563b0be50c043066e#diff-2f6e154f5c64301bbb1ca52d100d4aefR432)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [x] Update / Add Unit Tests
- [x] Update / Add Integration Tests

### CODE REVIEW

**Comment by shaundmorris** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java  -1
         

Clones added
============
- catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/plugins/LocationUpdateFieldTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Codice/alliance/pullRequest?prid=5728841&bid=18741571)

**Comment by shaundmorris** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java  -1
         

Clones added
============
- catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/plugins/LocationUpdateFieldTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Codice/alliance/pullRequest?prid=5728841&bid=18741571)

**Comment by jrnorth** [comment]
build now

**Comment by jrnorth** [comment]
[2020-06-22T17:48:28.393Z] [ERROR] Error retrieving http://nexus3.phx.connexta.com/repository/nvd/feeds/json/cve/1.0/nvdcve-1.0-modified.json.gz; received response code 502.
[2020-06-22T17:48:28.393Z] [ERROR] Download Failed for NVD CVE - Modified
10:48:28  Some CVEs may not be reported. Reason: Download failed, unable to copy 'http://nexus3.phx.connexta.com/repository/nvd/feeds/json/cve/1.0/nvdcve-1.0-modified.json.gz' to '/tmp/dctempeb70e9ed-9aa5-4b20-894b-c688adb2e857/cveModified_1014923695791374481.json.gz'
[2020-06-22T17:48:28.393Z] [ERROR] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[2020-06-22T17:48:28.394Z] [ERROR] Failed to execute goal org.owasp:dependency-check-maven:5.3.1:check (default-cli) on project alliance: Execution default-cli of goal org.owasp:dependency-check-maven:5.3.1:check failed. NullPointerException -> [Help 1]
[2020-06-22T17:48:28.394Z] [ERROR] 
[2020-06-22T17:48:28.394Z] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[2020-06-22T17:48:28.394Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[2020-06-22T17:48:28.394Z] [ERROR] 
[2020-06-22T17:48:28.394Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[2020-06-22T17:48:28.394Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by jrnorth** [comment]
build now

**Comment by shaundmorris** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java  -1
         

Clones added
============
- catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/plugins/LocationUpdateFieldTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Codice/alliance/pullRequest?prid=5728841&bid=18741571)

**Comment by jrnorth** [comment]
build now

**Comment by jrnorth** [comment]
build now

**Comment by jlcsmith** [comment]
Looks like CI is failing on tests
```
11:39:42  Tests in error: 
11:39:42    VideoTest.testStreamingVideo:135 » ConditionTimeout Condition with alias 'The ...
11:39:42  
```

**Comment by jrnorth** [comment]
build now

**Comment by shaundmorris** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java  -1
         

Clones added
============
- catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/plugins/LocationUpdateFieldTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Codice/alliance/pullRequest?prid=5728841&bid=18741571)

**Comment by jrnorth** [comment]
build now

**Comment by jlcsmith** [comment]
🎉  Hero Successful 🎉 
- streamed multiple videos
- verified parent/child metacards created
- verified metacards have locations and frame center geometries

**Pull request merged**
